// HOW-TO: Apply Gaussian Blur to JPEG and Save as PDF in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.ImageFilters.FilterOptions;

class Program
{
    static void Main()
    {
        string inputPath = "input.jpg";
        string pdfOutputPath = "output/output.pdf";

        try
        {
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(pdfOutputPath));

            using (Image image = Image.Load(inputPath))
            {
                RasterImage rasterImage = (RasterImage)image;

                var blurOptions = new GaussianBlurFilterOptions();
                rasterImage.Filter(rasterImage.Bounds, blurOptions);

                var pdfOptions = new PdfOptions();
                rasterImage.Save(pdfOutputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to soften a photo before embedding it in a PDF report generated by a C# application.
 * 2. When you want to create a printable PDF brochure that includes blurred background images for a professional look.
 * 3. When you must preprocess scanned JPEG images with a Gaussian blur to reduce noise before converting them to PDF for archival.
 * 4. When an automated workflow requires converting a batch of raster images to PDF while applying a consistent blur effect using Aspose.Imaging in .NET.
 * 5. When you are building a web service that receives user‑uploaded images, applies a blur filter for privacy, and returns the result as a PDF document.
 */
