// HOW-TO: Convert BMP Image to PDF Using Aspose.Imaging Save Method in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output file paths
            string inputPath = @"C:\temp\input.bmp";
            string outputPath = @"C:\temp\output.pdf";

            // Verify that the input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the BMP image
            using (Image image = Image.Load(inputPath))
            {
                // Set up PDF export options
                var pdfOptions = new PdfOptions();

                // Save the image as a PDF
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed a legacy BMP diagram into a PDF report generated by a C# application.
 * 2. When a batch process must convert scanned BMP files to searchable PDF documents for archiving.
 * 3. When an automated workflow requires saving a BMP logo as a PDF to preserve vector‑like quality for printing.
 * 4. When a web service receives BMP uploads and must return them as PDF files for client compatibility.
 * 5. When you want to programmatically create PDF invoices that include BMP product images using Aspose.Imaging in .NET.
 */
