// HOW-TO: Convert BMP Image to PDF Using Aspose.Imaging in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = Path.Combine("Input", "input.bmp");
            string outputPath = Path.Combine("Output", "output.pdf");

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            using (PdfOptions pdfOptions = new PdfOptions())
            {
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed a legacy BMP graphic into a PDF report generated by a C# application.
 * 2. When a desktop utility must batch‑convert scanned BMP files to searchable PDF documents for archiving.
 * 3. When an automated workflow creates PDF invoices that include company logos stored as BMP images.
 * 4. When a web service receives BMP uploads and must return them as PDF files for cross‑platform viewing.
 * 5. When a migration script replaces BMP assets with PDF equivalents to reduce file‑size and improve compatibility in a .NET project.
 */
