// HOW-TO: Create 200x200 BMP Thumbnail PDF With Median Filter In C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = "Input\\sample.bmp";
            string outputPath = "Output\\thumbnail.pdf";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load BMP image
            using (Image image = Image.Load(inputPath))
            {
                // Cast to RasterImage for processing
                RasterImage raster = (RasterImage)image;

                // Apply median filter with size 5
                raster.Filter(raster.Bounds, new Aspose.Imaging.ImageFilters.FilterOptions.MedianFilterOptions(5));

                // Resize to 200x200 pixels
                raster.Resize(200, 200);

                // Save as PDF thumbnail
                PdfOptions pdfOptions = new PdfOptions();
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to generate a small PDF preview of a large BMP for a document management system.
 * 2. When you want to apply noise reduction to a BMP before creating a thumbnail for a web gallery.
 * 3. When you must resize high‑resolution BMP images to a fixed 200×200 size for consistent UI thumbnails.
 * 4. When you need to embed a filtered BMP thumbnail into a PDF report generated by a .NET application.
 * 5. When you are automating batch processing of BMP files to produce PDF thumbnails for archival purposes.
 */
