using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Wrap the whole logic to catch unexpected errors
        try
        {
            // Hard‑coded input and output directories (network share paths)
            string inputDirectory = @"\\myserver\share\input";
            string outputDirectory = @"\\myserver\share\output";

            // Ensure the output directory exists (creates it if missing)
            Directory.CreateDirectory(outputDirectory);

            // Get all BMP files in the input directory
            string[] bmpFiles = Directory.GetFiles(inputDirectory, "*.bmp");

            foreach (string inputPath in bmpFiles)
            {
                // Verify the input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Build the corresponding PDF output path
                string outputFileName = Path.GetFileNameWithoutExtension(inputPath) + ".pdf";
                string outputPath = Path.Combine(outputDirectory, outputFileName);

                // Ensure the directory for the output file exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                // Load the BMP image
                using (Image image = Image.Load(inputPath))
                {
                    // Prepare PDF export options
                    var pdfOptions = new PdfOptions();

                    // Save the image as PDF
                    image.Save(outputPath, pdfOptions);
                }

                // Stream the generated PDF back to the client.
                // In this console example we simply write the PDF bytes to stdout.
                // In a real service you would write the stream to the HTTP response.
                using (FileStream pdfStream = File.OpenRead(outputPath))
                {
                    pdfStream.CopyTo(Console.OpenStandardOutput());
                }
            }
        }
        catch (Exception ex)
        {
            // Report any error without crashing
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a web service must batch‑convert legacy BMP scans stored on a network share into searchable PDF documents and return them directly to a browser client.
 * 2. When an enterprise document‑management system needs to ingest BMP images from a shared folder, transform them into PDF for archival, and stream the PDFs over an API call.
 * 3. When a Windows service automates the conversion of BMP graphics generated by a legacy imaging device into PDF reports that are then sent to downstream applications via HTTP streaming.
 * 4. When a cloud‑based file‑conversion microservice reads BMP files from a mapped network share, uses Aspose.Imaging to produce PDF files, and pipes the PDF bytes back to the requesting client without writing temporary files.
 * 5. When a compliance workflow requires converting BMP screenshots captured on a shared drive into PDF format for electronic signatures, and the PDFs must be delivered instantly to the user's web session.
 */