// HOW-TO: Sharpen PNG Image and Convert to PDF in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.ImageFilters.FilterOptions;
using Aspose.Imaging.FileFormats.Pdf;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "Input/input.png";
        string outputPath = "Output/output.pdf";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

        try
        {
            using (RasterImage raster = (RasterImage)Image.Load(inputPath))
            {
                raster.Filter(raster.Bounds, new SharpenFilterOptions());

                using (MemoryStream ms = new MemoryStream())
                {
                    PdfOptions pdfOptions = new PdfOptions();
                    raster.Save(ms, pdfOptions);
                    Console.WriteLine($"PDF generated, size: {ms.Length} bytes");
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to enhance a PNG screenshot with a sharpening filter before embedding it in a PDF report generated by a C# application.
 * 2. When you want to programmatically convert high‑resolution PNG scans of documents into PDF files while improving image clarity for printing.
 * 3. When you are building a web service that receives PNG uploads, sharpens them, and returns the result as a PDF stream without writing temporary files to disk.
 * 4. When you need to batch‑process product‑photo PNGs, apply a sharpen filter, and create PDF catalogs directly in memory for faster performance.
 * 5. When you are integrating Aspose.Imaging into a C# workflow to transform PNG graphics into PDF assets for archival, ensuring the images are sharpened for better readability.
 */
