// HOW-TO: Resize PNG to 1200x800 and Convert to PDF in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "input.png";
            string outputPath = "output.pdf";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (RasterImage image = (RasterImage)Image.Load(inputPath))
            {
                image.Resize(1200, 800);
                PdfOptions pdfOptions = new PdfOptions();
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to shrink a high‑resolution PNG to a standard 1200×800 size before embedding it in a PDF report generated by a C# application.
 * 2. When you must convert user‑uploaded PNG screenshots into PDF documents while ensuring the images fit a predefined page layout.
 * 3. When automating the creation of printable PDFs from PNG assets, and you need the images resized to avoid oversized files.
 * 4. When preparing product catalog images by resizing PNG files to 1200×800 and saving them directly as PDF pages using Aspose.Imaging in .NET.
 * 5. When archiving PNG graphics from a web portal into PDF format and require a consistent image dimension for easy viewing across devices.
 */
