using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.ImageFilters.FilterOptions;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "Input/sample.png";
        string outputPath = "Output/output.pdf";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

        try
        {
            using (Image image = Image.Load(inputPath))
            {
                RasterImage raster = (RasterImage)image;

                // Resize to 1200x800
                raster.Resize(1200, 800);

                // Apply median filter with size 3
                raster.Filter(raster.Bounds, new MedianFilterOptions(3));

                // Save as PDF
                PdfOptions pdfOptions = new PdfOptions();
                raster.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a web application needs to generate printable PDFs from user‑uploaded PNG screenshots, resizing them to 1200×800 and smoothing noise with a median filter before conversion.
 * 2. When an e‑commerce platform wants to create standardized product catalog pages by converting high‑resolution PNG product images into PDF brochures with consistent dimensions and reduced artifacts.
 * 3. When a document management system processes scanned PNG receipts, resizing them for storage efficiency, applying a median filter to improve readability, and saving them as searchable PDF files.
 * 4. When a mobile app backend prepares PNG graphics for email newsletters, scaling them to a fixed 1200×800 size, denoising with a median filter, and embedding them in PDF attachments.
 * 5. When a reporting tool automatically transforms PNG charts generated by analytics into PDF reports, ensuring uniform size and clean visual quality through resizing and median filtering.
 */