// HOW-TO: Add Semi Transparent Text Watermark to BMP Image in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.Brushes;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "input.bmp";
        string outputPath = "output.bmp";
        byte opacity = 128; // 50% opacity
        string watermarkText = "Sample Watermark";

        try
        {
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (var image = Image.Load(inputPath))
            {
                var raster = (RasterImage)image;
                var graphics = new Graphics(raster);
                Aspose.Imaging.Font font = new Aspose.Imaging.Font("Arial", 24);
                Color brushColor = Color.FromArgb(opacity, 255, 255, 255);
                using (var brush = new SolidBrush(brushColor))
                {
                    SizeF textSize = graphics.MeasureString(watermarkText, font, new SizeF(raster.Width, raster.Height), null);
                    float margin = 10f;
                    float x = raster.Width - textSize.Width - margin;
                    float y = raster.Height - textSize.Height - margin;
                    graphics.DrawString(watermarkText, font, brush, x, y);
                }
                var bmpOptions = new BmpOptions();
                raster.Save(outputPath, bmpOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to protect a BMP product photo with a copyright notice before publishing online.
 * 2. When you want to embed a client’s logo or custom text onto scanned BMP documents for internal tracking.
 * 3. When you must add a timestamp or batch identifier as a semi‑transparent watermark to BMP images generated by an automated imaging system.
 * 4. When you need to create watermarked BMP assets for a game’s UI while preserving the original resolution and file format.
 * 5. When you are required to apply a semi‑transparent disclaimer to BMP screenshots for compliance reporting.
 */
