using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Emf;
using Aspose.Imaging;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded directory containing EMF files
            string inputDir = @"C:\EmfImages";

            // Retrieve all .emf files in the directory
            string[] files = Directory.GetFiles(inputDir, "*.emf");

            foreach (string inputPath in files)
            {
                // Verify the input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Load the image using Aspose.Imaging
                using (Image image = Image.Load(inputPath))
                {
                    // Cast to EmfImage for cropping
                    EmfImage emf = image as EmfImage;
                    if (emf == null)
                    {
                        Console.Error.WriteLine($"Not an EMF image: {inputPath}");
                        continue;
                    }

                    // Define integer crop bounds (example: 10‑pixel inset on each side)
                    int left = 10;
                    int top = 10;
                    int width = emf.Width - 20;
                    int height = emf.Height - 20;

                    // Ensure the crop rectangle is valid
                    if (width <= 0 || height <= 0)
                    {
                        Console.Error.WriteLine($"Image too small to crop: {inputPath}");
                        continue;
                    }

                    // Perform the crop
                    var rect = new Rectangle(left, top, width, height);
                    emf.Crop(rect);

                    // Overwrite the original file
                    string outputPath = inputPath;
                    Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
                    emf.Save(outputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to automatically trim whitespace margins from a large collection of vector EMF diagrams before embedding them into a technical report.
 * 2. When a build pipeline must preprocess exported EMF icons by cropping a fixed pixel inset to ensure consistent visual alignment across a Windows application UI.
 * 3. When a document conversion tool has to batch‑crop EMF charts generated by legacy CAD software to remove unwanted borders before converting them to PDF.
 * 4. When a content management system requires a scheduled job that crops all EMF logos stored in a folder by a set number of pixels and overwrites the originals to save storage space.
 * 5. When an automated testing framework validates that every EMF asset in a repository conforms to a predefined canvas size by cropping each image with integer bounds and saving the changes in place.
 */