using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Emf;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Input directory containing EMF files
            string inputDirectory = "Input";

            // Validate input directory existence
            if (!Directory.Exists(inputDirectory))
            {
                Directory.CreateDirectory(inputDirectory);
                Console.WriteLine($"Input directory created at: {inputDirectory}. Add EMF files and rerun.");
                return;
            }

            // Get all EMF files in the directory
            string[] emfFiles = Directory.GetFiles(inputDirectory, "*.emf");

            foreach (string inputPath in emfFiles)
            {
                // Verify file existence
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    continue;
                }

                // Load the EMF image
                using (EmfImage emfImage = (EmfImage)Image.Load(inputPath))
                {
                    // Define integer crop bounds (e.g., remove 10 pixels from each side)
                    int left = 10;
                    int top = 10;
                    int width = emfImage.Width - 2 * left;
                    int height = emfImage.Height - 2 * top;

                    if (width <= 0 || height <= 0)
                    {
                        Console.Error.WriteLine($"Invalid crop dimensions for: {inputPath}");
                        continue;
                    }

                    // Create the cropping rectangle
                    Rectangle cropRect = new Rectangle(left, top, width, height);

                    // Perform cropping
                    emfImage.Crop(cropRect);

                    // Ensure output directory exists (same as input directory)
                    Directory.CreateDirectory(Path.GetDirectoryName(inputPath));

                    // Overwrite the original file with the cropped image
                    emfImage.Save(inputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to automatically remove unwanted margins from a large collection of EMF vector graphics generated by a CAD system before publishing them to a documentation portal.
 * 2. When a software solution must preprocess legacy EMF icons stored in a shared folder by trimming a fixed number of pixels from each side to fit a new UI layout without manually editing each file.
 * 3. When an automated build pipeline has to ensure that all EMF diagrams in a resource directory conform to a specific canvas size by cropping them with integer bounds and overwriting the originals.
 * 4. When a migration tool converts EMF reports into a standardized format and must batch‑crop the images to eliminate white space introduced during export.
 * 5. When a desktop application needs to clean up scanned EMF signatures by programmatically cropping a uniform border from every file in a user‑selected folder using C# and Aspose.Imaging.
 */