using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

public class Program
{
    public static void Main(string[] args)
    {
        try
        {
            string inputDirectory = "Input";
            string outputDirectory = "Output";

            string[] emfFiles = Directory.GetFiles(inputDirectory, "*.emf");

            int index = 1;
            foreach (var emfPath in emfFiles)
            {
                if (!File.Exists(emfPath))
                {
                    Console.Error.WriteLine($"File not found: {emfPath}");
                    continue;
                }

                string outputPath = Path.Combine(outputDirectory, $"{index}.png");
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                using (Image image = Image.Load(emfPath))
                {
                    var pngOptions = new PngOptions();
                    var vectorOptions = new EmfRasterizationOptions
                    {
                        PageSize = image.Size
                    };
                    pngOptions.VectorRasterizationOptions = vectorOptions;

                    image.Save(outputPath, pngOptions);
                }

                index++;
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to migrate a legacy collection of EMF vector graphics into web‑friendly PNG images with sequential filenames for a digital asset management system.
 * 2. When an automated build process must convert and rename EMF diagrams generated by a reporting tool into numbered PNG files for inclusion in PDF reports.
 * 3. When a batch job has to prepare EMF icons for a mobile app by rasterizing them to PNG and assigning simple numeric names for easier localization.
 * 4. When a data‑import script must standardize user‑uploaded EMF files into a consistent PNG format and store them in an output folder with incremental numbering for indexing.
 * 5. When a migration utility has to rename and rasterize EMF files from an old Windows application into sequential PNG files for archival in a cloud storage bucket.
 */