using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string baseDir = Directory.GetCurrentDirectory();
            string inputDirectory = Path.Combine(baseDir, "Input");
            string outputDirectory = Path.Combine(baseDir, "Output");

            if (!Directory.Exists(inputDirectory))
            {
                Directory.CreateDirectory(inputDirectory);
                Console.WriteLine($"Input directory created at: {inputDirectory}. Add files and rerun.");
                return;
            }

            if (!Directory.Exists(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            string[] files = Directory.GetFiles(inputDirectory, "*.emf");
            int index = 1;

            foreach (var inputPath in files)
            {
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                string outputFileName = $"{index}.png";
                string outputPath = Path.Combine(outputDirectory, outputFileName);
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                using (Image image = Image.Load(inputPath))
                {
                    var vectorOptions = new VectorRasterizationOptions
                    {
                        BackgroundColor = Color.White,
                        PageSize = image.Size
                    };

                    var pngOptions = new PngOptions
                    {
                        VectorRasterizationOptions = vectorOptions
                    };

                    image.Save(outputPath, pngOptions);
                }

                index++;
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to migrate a legacy collection of vector‑based EMF diagrams into web‑friendly PNG images with sequential filenames for easy indexing.
 * 2. When an automated build process must convert and rename dozens of EMF reports generated by a reporting engine into numbered PNG files for inclusion in a PDF batch.
 * 3. When a migration script has to prepare EMF assets for a mobile app by rasterizing them to white‑background PNGs and giving each file a simple numeric name.
 * 4. When a document management system requires batch processing of user‑uploaded EMF files, converting them to PNG thumbnails and storing them with incremental identifiers.
 * 5. When a CI/CD pipeline needs to validate that all EMF icons in a source folder are correctly rendered as PNGs with consistent sizing and sequential naming before deployment.
 */