using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Jpeg;

public class Program
{
    public static void Main(string[] args)
    {
        try
        {
            string baseDir = Directory.GetCurrentDirectory();
            string inputDirectory = Path.Combine(baseDir, "Input");
            string outputDirectory = Path.Combine(baseDir, "Output");

            if (!Directory.Exists(inputDirectory))
            {
                Directory.CreateDirectory(inputDirectory);
                Console.WriteLine($"Input directory created at: {inputDirectory}. Add files and rerun.");
                return;
            }

            if (!Directory.Exists(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            string[] files = Directory.GetFiles(inputDirectory, "*.emf");

            foreach (var inputPath in files)
            {
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                string outputPath = Path.Combine(outputDirectory, Path.ChangeExtension(Path.GetFileName(inputPath), ".jpg"));
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                using (Image image = Image.Load(inputPath))
                {
                    var jpegOptions = new JpegOptions
                    {
                        CompressionType = JpegCompressionMode.Progressive,
                        Quality = 100,
                        VectorRasterizationOptions = new VectorRasterizationOptions
                        {
                            BackgroundColor = Color.White,
                            PageWidth = image.Width,
                            PageHeight = image.Height,
                            TextRenderingHint = TextRenderingHint.SingleBitPerPixel,
                            SmoothingMode = SmoothingMode.None
                        }
                    };

                    image.Save(outputPath, jpegOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert a large collection of vector EMF diagrams into web‑friendly progressive JPEGs for faster page loads, this code automates the batch conversion using Aspose.Imaging for .NET.
 * 2. When an enterprise workflow requires exporting EMF reports generated by legacy applications into high‑quality JPEG thumbnails for email attachments, the program rasterizes each file with white background and saves it with progressive encoding.
 * 3. When a content management system must ingest user‑uploaded EMF logos and store them as progressive JPEGs to reduce bandwidth while preserving visual fidelity, the code provides a C# solution for bulk processing.
 * 4. When a digital asset pipeline needs to prepare EMF illustrations for archival in JPEG format with lossless‑looking quality and progressive rendering for preview viewers, this script handles the conversion and folder management automatically.
 * 5. When a developer is building a Windows service that nightly scans an input folder of EMF files and outputs progressive JPEGs for downstream analytics or reporting tools, the example demonstrates the required file handling and rasterization options.
 */