// HOW-TO: Batch Crop All EMF Files in a Folder Using C# Aspose Imaging (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging.FileFormats.Emf;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Hardcoded input directory containing EMF files.
            string inputDirectory = "Input";

            // Ensure the input directory exists.
            if (!Directory.Exists(inputDirectory))
            {
                Directory.CreateDirectory(inputDirectory);
                Console.WriteLine($"Created input directory: {inputDirectory}. Add EMF files and rerun.");
                return;
            }

            // Process all EMF files in the directory.
            string[] emfFiles = Directory.GetFiles(inputDirectory, "*.emf");
            foreach (string inputPath in emfFiles)
            {
                // Verify the file exists.
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    continue;
                }

                // Load the EMF image.
                using (Aspose.Imaging.Image image = Aspose.Imaging.Image.Load(inputPath))
                {
                    // Cast to EmfImage to access vector-specific methods.
                    Aspose.Imaging.FileFormats.Emf.EmfImage emfImage = (Aspose.Imaging.FileFormats.Emf.EmfImage)image;

                    // Define integer crop bounds (example: 10‑pixel inset on each side).
                    int left = 10;
                    int top = 10;
                    int width = emfImage.Width - 2 * left;
                    int height = emfImage.Height - 2 * top;

                    // Ensure width and height are positive.
                    if (width <= 0 || height <= 0)
                    {
                        Console.Error.WriteLine($"Invalid crop dimensions for file: {inputPath}");
                        continue;
                    }

                    // Create the cropping rectangle.
                    Aspose.Imaging.Rectangle cropRect = new Aspose.Imaging.Rectangle(left, top, width, height);

                    // Perform the crop.
                    emfImage.Crop(cropRect);

                    // Ensure the output directory exists (same as input directory here).
                    Directory.CreateDirectory(Path.GetDirectoryName(inputPath));

                    // Overwrite the original file with the cropped image.
                    emfImage.Save(inputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to remove unwanted borders from a large set of EMF icons before embedding them in a Windows application.
 * 2. When preparing EMF diagrams for printing and you must uniformly trim a fixed margin from every file in a folder.
 * 3. When automating the cleanup of vector assets generated by a CAD tool that adds a constant padding around each image.
 * 4. When creating a batch job that crops all EMF charts to a specific size so they fit into a PDF report without manual editing.
 * 5. When updating an existing image library by applying the same integer inset crop to every EMF file and overwriting the originals to save storage space.
 */
