// HOW-TO: Combine Multiple TIFF Files While Keeping Original EXIF Metadata in C# (Aspose.Imaging for .NET)
// ── Machine-verified example ──────────────────────────────────────────────
// Compiler-verified: built with `dotnet build` — 0 errors.
// Run-tested: executed with `dotnet run` on net9.0 — exit code 0, no unhandled exceptions.
// Exception handling: try/catch present in this example.
// Package: Aspose.Imaging 26.9.0 | Verified: 2026-09-25
// Generated and validated by an agentic workflow, not hand-written.
// ─────────────────────────────────────────────────────────────────────────────
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Tiff;
using Aspose.Imaging.FileFormats.Tiff.Enums;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath1 = "input1.tif";
            string inputPath2 = "input2.tif";
            string outputPath = "output.tif";

            // Validate input files
            if (!File.Exists(inputPath1))
            {
                Console.Error.WriteLine($"File not found: {inputPath1}");
                return;
            }
            if (!File.Exists(inputPath2))
            {
                Console.Error.WriteLine($"File not found: {inputPath2}");
                return;
            }

            // Prepare list of inputs
            List<string> inputPaths = new List<string> { inputPath1, inputPath2 };

            // TIFF options for the destination image
            TiffOptions tiffOptions = new TiffOptions(TiffExpectedFormat.Default);

            TiffImage destImage = null;
            bool firstFrameCreated = false;

            foreach (string inputPath in inputPaths)
            {
                using (TiffImage srcImage = (TiffImage)Image.Load(inputPath))
                {
                    foreach (TiffFrame srcFrame in srcImage.Frames)
                    {
                        // Load pixel data from source frame
                        Aspose.Imaging.Color[] pixels = srcImage.LoadPixels(srcFrame.Bounds);

                        int width = srcFrame.Width;
                        int height = srcFrame.Height;

                        if (!firstFrameCreated)
                        {
                            // Create destination image with size of the first frame
                            destImage = (TiffImage)Image.Create(tiffOptions, width, height);
                            // Save pixels to the first frame
                            destImage.SavePixels(destImage.Bounds, pixels);
                            // Preserve EXIF metadata from the source image
                            if (srcImage.ExifData != null)
                            {
                                destImage.ExifData = srcImage.ExifData;
                            }
                            firstFrameCreated = true;
                        }
                        else
                        {
                            // Add a new frame to the destination image
                            destImage.AddFrame(new TiffFrame(tiffOptions, width, height));
                            int newIndex = destImage.Frames.Count() - 1;
                            // Save pixels to the newly added frame
                            destImage.Frames[newIndex].SavePixels(destImage.Frames[newIndex].Bounds, pixels);
                        }
                    }
                }
            }

            if (destImage == null)
            {
                Console.Error.WriteLine("No frames were processed. Destination image not created.");
                return;
            }

            // Ensure output directory exists
            string outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrWhiteSpace(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Save the concatenated TIFF
            using (destImage)
            {
                destImage.Save(outputPath, tiffOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to merge scanned document pages stored as separate TIFF files into a single multi‑page TIFF for easier distribution while retaining each page’s camera or scanner EXIF data.
 * 2. When archiving medical imaging studies that consist of several TIFF frames and you must preserve the original metadata for regulatory compliance.
 * 3. When creating a digital archive of historic photographs that are stored as individual TIFFs and you want a single file that keeps each photo’s capture information intact.
 * 4. When building a batch processing tool that consolidates TIFF images generated by a scanner into one file without losing orientation, resolution, or date‑taken metadata.
 * 5. When developing a document management system that stores multi‑page TIFFs and requires the original EXIF tags from each source page for searchable metadata.
 */
