using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Tiff;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input TIFF file paths
            string inputPath1 = @"C:\Images\part1.tif";
            string inputPath2 = @"C:\Images\part2.tif";
            string inputPath3 = @"C:\Images\part3.tif";

            // Verify each input file exists
            if (!File.Exists(inputPath1))
            {
                Console.Error.WriteLine($"File not found: {inputPath1}");
                return;
            }
            if (!File.Exists(inputPath2))
            {
                Console.Error.WriteLine($"File not found: {inputPath2}");
                return;
            }
            if (!File.Exists(inputPath3))
            {
                Console.Error.WriteLine($"File not found: {inputPath3}");
                return;
            }

            // Load each TIFF as a TiffFrame
            TiffFrame frame1 = new TiffFrame(inputPath1);
            TiffFrame frame2 = new TiffFrame(inputPath2);
            TiffFrame frame3 = new TiffFrame(inputPath3);

            // Create a new multi‑frame TIFF image from the loaded frames
            using (TiffImage multiFrameTiff = new TiffImage(new TiffFrame[] { frame1, frame2, frame3 }))
            {
                // Hardcoded output path
                string outputPath = @"C:\Images\combined.tif";

                // Ensure the output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                // Save the combined TIFF
                multiFrameTiff.Save(outputPath);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to combine separate scanned pages saved as individual TIFF files into a single multi‑frame TIFF for streamlined document distribution using C# and Aspose.Imaging.
 * 2. When an application must programmatically assemble a series of medical imaging slices stored as TIFFs into one multi‑page TIFF for easier viewing in radiology software.
 * 3. When a workflow requires merging high‑resolution TIFF maps generated by different GIS tools into one file to simplify storage and retrieval in a .NET environment.
 * 4. When a batch‑processing script has to concatenate TIFF frames produced by a scanner into a single archive file before uploading to a cloud storage service.
 * 5. When a developer wants to create a multi‑page TIFF portfolio by reading individual TIFF assets and saving them as one image using Aspose.Imaging’s TiffFrame and TiffImage classes.
 */