using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Emf;
using Aspose.Imaging.FileFormats.Pdf;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "Input\\sample.emf";
        string outputPath = "Output\\sample.pdf";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

        try
        {
            using (Image image = Image.Load(inputPath))
            {
                // Obtain image size (EMF specific)
                Size imageSize = (image as EmfImage)?.Size ?? image.Size;

                var pdfOptions = new PdfOptions();

                var vectorOptions = new VectorRasterizationOptions
                {
                    BackgroundColor = Color.White,
                    PageSize = imageSize,
                    TextRenderingHint = TextRenderingHint.SingleBitPerPixel,
                    SmoothingMode = SmoothingMode.None
                };

                pdfOptions.VectorRasterizationOptions = vectorOptions;

                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer must transform EMF vector graphics generated by a CAD tool into a high‑resolution PDF for inclusion in printable technical manuals, ensuring the PDF retains crisp lines and embedded fonts.
 * 2. When an enterprise application needs to batch‑process user‑uploaded EMF logos and export them as PDF assets for a branding portal, preserving exact dimensions and font rendering.
 * 3. When a reporting service generates charts as EMF files and requires conversion to PDF so that the final reports can be viewed on any platform without losing vector fidelity or font information.
 * 4. When a document‑management system archives legacy EMF schematics and must store them as searchable PDF files with embedded fonts to meet compliance and accessibility standards.
 * 5. When a web‑based design tool saves drawings in EMF format and needs to provide a one‑click “Download as PDF” feature that produces a high‑resolution PDF with proper font embedding for end‑users.
 */