using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Tga;
using Aspose.Imaging.FileFormats.Bmp;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = "input.tga";
            string outputPath = "output.bmp";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the TGA image
            using (TgaImage tgaImage = (TgaImage)Image.Load(inputPath))
            {
                // Preserve original bits per pixel
                int originalBpp = tgaImage.BitsPerPixel;

                // Create BMP image with the same bit depth and no compression
                using (BmpImage bmpImage = new BmpImage(
                    tgaImage,
                    (ushort)originalBpp,
                    BitmapCompression.Rgb,
                    tgaImage.HorizontalResolution,
                    tgaImage.VerticalResolution))
                {
                    // Save as BMP, preserving alpha channel if present
                    bmpImage.Save(outputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a game developer needs to convert legacy TGA textures with alpha channels to BMP for compatibility with a Windows‑only rendering engine while keeping the original bit depth.
 * 2. When a desktop application must batch‑process user‑uploaded TGA screenshots and store them as BMP files for faster loading in a .NET image viewer.
 * 3. When a GIS specialist wants to preserve the exact color precision and transparency of satellite imagery saved as TGA before converting it to BMP for use in legacy mapping software.
 * 4. When an automated build pipeline has to transform TGA assets generated by a 3D modeling tool into BMP assets without losing the alpha channel for UI overlays.
 * 5. When a digital archivist needs to migrate TGA files from an old archive to BMP format while ensuring the original bits‑per‑pixel and resolution are retained for future reference.
 */