// HOW-TO: Convert JPEG to HTML5 Canvas and Embed in Markdown with C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hard‑coded paths
            string inputPath = @"C:\temp\sample.jpg";
            string canvasPath = @"C:\temp\canvas.html";
            string markdownPath = @"C:\temp\output.md";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directories exist
            Directory.CreateDirectory(Path.GetDirectoryName(canvasPath));
            Directory.CreateDirectory(Path.GetDirectoryName(markdownPath));

            // Load the JPEG image
            using (Image image = Image.Load(inputPath))
            {
                // Save only the <canvas> tag (no full HTML page)
                var canvasOptions = new Html5CanvasOptions
                {
                    FullHtmlPage = false,
                    CanvasTagId = "myCanvas"
                };

                image.Save(canvasPath, canvasOptions);
            }

            // Read the generated canvas HTML
            string canvasHtml = File.ReadAllText(canvasPath);

            // Write a Markdown file that embeds the canvas HTML directly
            using (var writer = new StreamWriter(markdownPath, false))
            {
                writer.WriteLine("# JPEG to HTML5 Canvas");
                writer.WriteLine();
                writer.WriteLine("The image below is rendered using an HTML5 canvas:");
                writer.WriteLine();
                writer.WriteLine(canvasHtml); // Raw HTML is allowed in Markdown
                writer.WriteLine();
                writer.WriteLine("*Generated by Aspose.Imaging*");
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to display a JPEG image on a web page using an HTML5 canvas inside a Markdown‑rendered document.
 * 2. When generating technical documentation that combines code examples with visual content without relying on external image files.
 * 3. When automating the conversion of a batch of JPEGs into self‑contained Markdown files for static site generators.
 * 4. When creating interactive tutorials where the image must be rendered via canvas for later manipulation with JavaScript.
 * 5. When embedding images in README files on platforms that support raw HTML within Markdown, ensuring the image is rendered consistently across browsers.
 */
