using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output file paths
            string inputPath = "input.tga";
            string outputPath = "output.png";

            // Verify that the input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");

            // Load the TGA image
            using (RasterImage image = (RasterImage)Image.Load(inputPath))
            {
                // Save the image as PNG, preserving the alpha channel
                var pngOptions = new PngOptions();
                image.Save(outputPath, pngOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a game developer needs to batch‑convert legacy TGA textures with transparency into PNGs for modern Unity assets, they can use this C# code with Aspose.Imaging to preserve the alpha channel.
 * 2. When a web designer receives client artwork in TGA format and must deliver web‑ready PNG files with transparent backgrounds, the example shows how to load and save the image while keeping the alpha channel intact.
 * 3. When an automation script processes scanned UI mockups stored as TGA files and stores them as PNGs for inclusion in a documentation pipeline, the code demonstrates the required file existence checks and directory creation in C#.
 * 4. When a desktop application needs to import user‑provided TGA icons and export them as PNGs for Windows shortcut overlays, this snippet illustrates using RasterImage and PngOptions to retain transparency.
 * 5. When a CI/CD build step converts TGA assets generated by a graphics pipeline into PNGs for cross‑platform deployment, the example provides a reliable way to perform the conversion in .NET while handling errors gracefully.
 */