// HOW-TO: Combine Multiple BMP Files into a Multi‑Page TIFF in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using System.Linq;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Tiff;
using Aspose.Imaging.FileFormats.Tiff.Enums;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Hardcoded input BMP file paths
            string[] inputPaths = new string[]
            {
                "Input\\image1.bmp",
                "Input\\image2.bmp",
                "Input\\image3.bmp"
            };

            // Verify each input file exists
            foreach (string inputPath in inputPaths)
            {
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }
            }

            // Hardcoded output TIFF path
            string outputPath = "Output\\merged.tif";

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load first image to obtain dimensions
            using (Image firstImg = Image.Load(inputPaths[0]))
            {
                int width = firstImg.Width;
                int height = firstImg.Height;

                using (TiffOptions tiffOptions = new TiffOptions(TiffExpectedFormat.Default))
                {
                    using (TiffImage tiff = (TiffImage)Image.Create(tiffOptions, width, height))
                    {
                        // Copy pixels from first image to the first frame
                        using (RasterImage rasterFirst = (RasterImage)firstImg)
                        {
                            Color[] pixelsFirst = rasterFirst.LoadPixels(firstImg.Bounds);
                            tiff.ActiveFrame.SavePixels(tiff.ActiveFrame.Bounds, pixelsFirst);
                        }

                        // Process remaining images
                        for (int i = 1; i < inputPaths.Length; i++)
                        {
                            using (Image img = Image.Load(inputPaths[i]))
                            {
                                int srcWidth = img.Width;
                                int srcHeight = img.Height;

                                // Add a new frame with source dimensions
                                tiff.AddFrame(new TiffFrame(tiffOptions, srcWidth, srcHeight));
                                tiff.ActiveFrame = tiff.Frames[tiff.Frames.Count() - 1];

                                using (RasterImage raster = (RasterImage)img)
                                {
                                    Color[] pixels = raster.LoadPixels(img.Bounds);
                                    tiff.ActiveFrame.SavePixels(tiff.ActiveFrame.Bounds, pixels);
                                }
                            }
                        }

                        // Save the multi-page TIFF
                        tiff.Save(outputPath);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to merge scanned BMP pages into a single multi‑page TIFF for easy viewing or printing.
 * 2. When an application must archive a series of BMP screenshots as a compact, paginated TIFF document.
 * 3. When converting BMP assets from a legacy system into a multi‑page TIFF to be imported into a document management workflow.
 * 4. When generating a multi‑page TIFF report that combines multiple BMP charts or diagrams generated by a C# service.
 * 5. When preparing a batch of BMP medical images for storage in a single TIFF file to simplify retrieval and compliance.
 */
