using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Emf;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = @"C:\Images\multpage.emf";
            string outputDirectory = @"C:\Images\Output";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists
            Directory.CreateDirectory(outputDirectory);

            // Load the EMF document
            using (Image image = Image.Load(inputPath))
            {
                // Try to treat the image as a multipage image
                IMultipageImage multipage = image as IMultipageImage;
                int pageCount = multipage?.PageCount ?? 1; // EMF is usually single‑page

                for (int i = 0; i < pageCount; i++)
                {
                    // Build output file name for each page
                    string outputPath = Path.Combine(outputDirectory, $"page_{i + 1}.png");

                    // Ensure the directory for the output file exists
                    Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                    // Prepare PNG save options with vector rasterization
                    var pngOptions = new PngOptions
                    {
                        VectorRasterizationOptions = new EmfRasterizationOptions
                        {
                            PageSize = image.Size
                        },
                        // Export only the current page
                        MultiPageOptions = new MultiPageOptions(new IntRange(i, i + 1))
                    };

                    // Save the current page as PNG
                    image.Save(outputPath, pngOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a Windows desktop application needs to display each page of a multi‑page EMF report as raster PNG thumbnails in a gallery view.
 * 2. When an automated document‑processing pipeline must extract individual pages from a vector‑based EMF presentation and store them as PNG images for web publishing.
 * 3. When a C# service converts EMF drawings generated by CAD tools into separate PNG files for inclusion in PDF invoices.
 * 4. When a batch job prepares EMF‑based marketing assets for email campaigns by rasterizing each page to PNG to ensure compatibility with email clients.
 * 5. When a legacy system exports multi‑page EMF charts and a developer needs to split them into per‑page PNG files for archival in a content‑management system.
 */