using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Emf;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "C:\\Images\\input.emf";
        string outputPath = "C:\\Images\\output.svg";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

        try
        {
            using (EmfImage emfImage = (EmfImage)Image.Load(inputPath))
            {
                SvgOptions saveOptions = new SvgOptions();
                saveOptions.TextAsShapes = true;

                EmfRasterizationOptions rasterOptions = new EmfRasterizationOptions();
                rasterOptions.BackgroundColor = Color.WhiteSmoke;
                rasterOptions.PageSize = emfImage.Size;
                rasterOptions.RenderMode = EmfRenderMode.Auto;
                rasterOptions.BorderX = 50;
                rasterOptions.BorderY = 50;

                saveOptions.VectorRasterizationOptions = rasterOptions;

                emfImage.Save(outputPath, saveOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert legacy EMF graphics generated by Windows applications into responsive SVG files for inclusion in HTML pages, while ensuring any raster content is embedded as Base64 to avoid external image references.
 * 2. When a .NET application must generate printable vector assets from EMF logos and embed them directly into an SVG email template without relying on separate image files.
 * 3. When a reporting tool has to export chart drawings stored as EMF into SVG format for interactive dashboards, preserving the original appearance by rasterizing complex elements and encoding them as Base64.
 * 4. When a migration script has to batch‑process a folder of EMF icons and produce self‑contained SVG icons that can be cached by browsers without additional HTTP requests.
 * 5. When a developer is building a document conversion service that transforms Windows Metafile diagrams into SVG for PDF generation, and needs the raster parts encoded in Base64 to keep the SVG file portable.
 */