using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Emf;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "input.emf";
            string outputPath = "output.png";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                // Configure vector rasterization options for EMF
                EmfRasterizationOptions vectorOptions = new EmfRasterizationOptions
                {
                    PageSize = image.Size,
                    BackgroundColor = Aspose.Imaging.Color.White
                };

                // Configure PNG options with DPI settings
                PngOptions pngOptions = new PngOptions
                {
                    VectorRasterizationOptions = vectorOptions,
                    ResolutionSettings = new Aspose.Imaging.ResolutionSetting(300, 300) // DPI X, DPI Y
                };

                image.Save(outputPath, pngOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert a Windows Metafile (EMF) diagram generated by a reporting tool into a high‑resolution PNG for web display, preserving vector quality at 300 DPI.
 * 2. When an application must batch‑process legacy EMF icons and export them as PNG thumbnails with a specific DPI to ensure consistent sizing across different devices.
 * 3. When a document‑generation service has to embed a vector‑based chart (EMF) into a PDF and first rasterizes it to a PNG at a known DPI for accurate printing.
 * 4. When a GIS system stores map overlays in EMF format and requires conversion to PNG with a defined DPI for use in mobile mapping apps.
 * 5. When a developer is creating an automated build pipeline that validates graphic assets by converting EMF assets to PNG at 300 DPI to compare against baseline images.
 */