using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Eps;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = "sample.eps";
            string outputPath = "preview.png";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the EPS image
            using (var epsImage = (EpsImage)Image.Load(inputPath))
            {
                // Retrieve the preview image (default format)
                var previewImage = epsImage.GetPreviewImage();

                if (previewImage == null)
                {
                    Console.Error.WriteLine("No preview image found in the EPS file.");
                    return;
                }

                // Save the preview image as PNG
                var pngOptions = new PngOptions();
                previewImage.Save(outputPath, pngOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to extract the embedded preview image from an EPS file to generate a thumbnail for a document management system.
 * 2. When a developer wants to convert the EPS preview to a PNG for inclusion in a PDF report generated by a C# application.
 * 3. When a developer must verify that an EPS file contains a preview image before sending it to a client that only supports raster formats.
 * 4. When a developer is building an automated workflow that extracts EPS previews and stores them in a database for quick image search.
 * 5. When a developer needs to replace missing EPS preview data by generating a PNG preview using Aspose.Imaging for legacy print assets.
 */