using System;
using System.IO;
using System.Collections.Generic;
using System.Reflection;
using System.Text.Json;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Bmp;

class Program
{
    static void Main()
    {
        // Hardcoded input and output paths
        string inputPath = "input.bmp";
        string outputPath = "output.json";

        try
        {
            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");

            // Load BMP image
            using (BmpImage image = (BmpImage)Image.Load(inputPath))
            {
                // Retrieve EXIF data if available
                var exifData = image.Metadata?.ExifData;

                var exifDictionary = new Dictionary<string, object>();

                if (exifData != null)
                {
                    // Use reflection to read all public readable properties
                    PropertyInfo[] properties = exifData.GetType().GetProperties(BindingFlags.Public | BindingFlags.Instance);
                    foreach (var prop in properties)
                    {
                        if (prop.CanRead)
                        {
                            try
                            {
                                object value = prop.GetValue(exifData);
                                // Skip null values to keep JSON clean
                                if (value != null)
                                {
                                    exifDictionary[prop.Name] = value;
                                }
                            }
                            catch
                            {
                                // Ignore any property that throws during get
                            }
                        }
                    }
                }

                // Serialize dictionary to JSON
                string json = JsonSerializer.Serialize(exifDictionary, new JsonSerializerOptions { WriteIndented = true });

                // Write JSON to output file
                File.WriteAllText(outputPath, json);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to audit camera settings stored in BMP files generated by industrial imaging equipment and export them to a JSON report for compliance tracking.
 * 2. When a photo management application must read EXIF tags from BMP screenshots and serialize them to JSON to enable searchable metadata in a database.
 * 3. When a GIS system imports BMP terrain tiles and requires the embedded EXIF geolocation data to be extracted and saved as JSON for mapping services.
 * 4. When a digital forensics tool analyzes BMP evidence files and extracts all available EXIF metadata into a JSON file for easy review and automated parsing.
 * 5. When a batch processing script processes a folder of BMP assets and creates JSON side‑car files containing EXIF information to feed into a machine‑learning pipeline.
 */