using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Bmp;
using Aspose.Imaging.FileFormats.Jpeg;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "input.bmp";
            string outputPath = "output\\metadata.json";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                BmpImage bmp = image as BmpImage;
                string json;

                if (bmp != null && bmp.ExifData != null)
                {
                    var exif = bmp.ExifData;
                    json = "{" +
                           $"\"Make\":\"{exif.Make ?? string.Empty}\"," +
                           $"\"ExposureTime\":\"{exif.ExposureTime}\"," +
                           $"\"FNumber\":\"{exif.FNumber}\"," +
                           $"\"ISOSpeed\":\"{exif.ISOSpeed}\"," +
                           $"\"FocalLength\":\"{exif.FocalLength}\"" +
                           "}";
                }
                else
                {
                    json = "{}";
                }

                File.WriteAllText(outputPath, json);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to catalog camera settings from BMP images generated by a medical imaging device and store them in a JSON file for downstream analytics.
 * 2. When an application must validate that uploaded BMP files contain required EXIF fields such as Make, ExposureTime, and ISO before processing them further.
 * 3. When a photo‑management system wants to generate a lightweight JSON manifest of EXIF metadata from BMP assets to display in a web UI.
 * 4. When a batch‑processing script extracts EXIF data from BMP files to feed into a machine‑learning pipeline that expects JSON input.
 * 5. When a developer is building a C# utility that archives BMP images along with their metadata in JSON format for compliance auditing.
 */