// HOW-TO: Flip CorelDRAW Image Horizontally and Save as TIFF in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Tiff;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = "C:\\Images\\sample.cdr";
            string outputPath = "C:\\Images\\sample_flipped.tif";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the CorelDRAW file
            using (Image image = Image.Load(inputPath))
            {
                // Flip horizontally
                image.RotateFlip(RotateFlipType.RotateNoneFlipX);

                // Set up TIFF save options
                var tiffOptions = new TiffOptions(Aspose.Imaging.FileFormats.Tiff.Enums.TiffExpectedFormat.Default);

                // Save the flipped image as TIFF
                image.Save(outputPath, tiffOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a printing workflow requires a mirrored version of a CorelDRAW design to be sent to a press that expects TIFF files.
 * 2. When an e‑commerce platform needs to generate right‑to‑left product mockups from original CDR artwork and store them as TIFF for high‑resolution previews.
 * 3. When a document management system must archive CorelDRAW drawings as lossless TIFF images after applying a horizontal flip for compliance with legacy layout standards.
 * 4. When a batch‑processing tool needs to automatically convert multiple CDR files to TIFF while correcting orientation for downstream GIS or CAD applications.
 * 5. When a developer wants to programmatically flip a logo created in CorelDRAW and export it as a TIFF to embed in a PDF report generated by .NET.
 */
