using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = @"C:\temp\input.tif";
            string outputPath = @"C:\temp\output.jpg";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the TIFF image
            using (Image image = Image.Load(inputPath))
            {
                // Save as JPEG with default options
                image.Save(outputPath, new JpegOptions());
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer must convert high‑resolution TIFF scans of invoices to JPEG files for quick display in a web portal using C# and Aspose.Imaging.
 * 2. When an automated workflow needs to transform multi‑page TIFF medical images into single‑page JPEG thumbnails for integration with electronic health record systems.
 * 3. When a desktop utility written in .NET has to read a TIFF photograph from a user‑specified folder and save it as a JPEG to reduce file size before uploading to cloud storage.
 * 4. When a legacy reporting tool requires TIFF charts to be saved as JPEG so they can be embedded in PDF reports generated by a C# application.
 * 5. When a batch‑processing script must verify the existence of a TIFF file, create the output directory if needed, and then use Aspose.Imaging to export the image as a standard JPEG with default settings.
 */