// HOW-TO: Convert EPS to PDF Using Aspose.Imaging in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            string inputPath = "input.eps";
            string outputPath = "output\\output.pdf";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                var pdfOptions = new PdfOptions();
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed a vector EPS illustration into a PDF report generated by a .NET application.
 * 2. When a web service receives EPS files from designers and must deliver PDF versions to clients without manual conversion.
 * 3. When automating batch processing of EPS assets to create PDF portfolios for archival or printing workflows.
 * 4. When integrating Aspose.Imaging into a document management system to convert uploaded EPS drawings to searchable PDF files.
 * 5. When building a desktop tool that lets users select an EPS file and instantly export it as a PDF for easy sharing.
 */
