using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output file paths
            string inputPath = @"C:\temp\sample.cdr";
            string outputPath = @"C:\temp\sample.png";

            // Verify that the input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the CorelDRAW file
            using (Image image = Image.Load(inputPath))
            {
                // Use default PNG options
                var pngOptions = new PngOptions();

                // Save the image as PNG
                image.Save(outputPath, pngOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert legacy CorelDRAW (.cdr) artwork into web‑ready PNG images for display on a website without manually opening the design software.
 * 2. When an automated build script must batch‑process CDR files and generate PNG thumbnails for a digital asset management system using C# and Aspose.Imaging.
 * 3. When a desktop application requires on‑the‑fly conversion of user‑uploaded CorelDRAW files to PNG so they can be previewed in a Windows Forms UI.
 * 4. When a cloud service needs to transform vector‑based CDR diagrams into raster PNG files for inclusion in PDF reports generated by a .NET backend.
 * 5. When a migration tool extracts graphics from old CorelDRAW projects and saves them as PNG using default settings to preserve original colors for archival purposes.
 */