// HOW-TO: Convert DjVu Document to PDF with Author Metadata in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Djvu;
using Aspose.Imaging.FileFormats.Pdf;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "Input\\document.djvu";
            string outputPath = "Output\\output.pdf";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (DjvuImage djvu = (DjvuImage)Image.Load(inputPath))
            {
                using (PdfOptions pdfOptions = new PdfOptions())
                {
                    pdfOptions.PdfDocumentInfo = new PdfDocumentInfo();
                    pdfOptions.PdfDocumentInfo.Author = "Automated";

                    djvu.Save(outputPath, pdfOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to archive a multi‑page DjVu scan as a searchable PDF and automatically tag it with an author name for document management systems.
 * 2. When a batch job must convert incoming DjVu files to PDF for downstream processing while ensuring the PDF metadata reflects that the file was generated by an automated workflow.
 * 3. When you are building a C# service that creates PDF reports from DjVu source files and wants to embed the creator’s name to satisfy compliance or audit requirements.
 * 4. When a web application needs to preview DjVu documents in browsers that only support PDF, and you want each generated PDF to carry a consistent author identifier.
 * 5. When integrating legacy DjVu archives into a modern .NET application, you can convert all pages to a single PDF and set the author field to “Automated” to distinguish programmatic conversions from manual ones.
 */
