// HOW-TO: Convert EMF File to PDF with Vector Rasterization in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = "Input\\sample.emf";
            string outputPath = "Output\\sample.pdf";

            // Validate input file existence
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the EMF image
            using (Image image = Image.Load(inputPath))
            {
                // Prepare PDF options with vector rasterization settings
                PdfOptions pdfOptions = new PdfOptions();

                VectorRasterizationOptions vectorOptions = new VectorRasterizationOptions
                {
                    BackgroundColor = Color.White,
                    PageSize = new SizeF(image.Width, image.Height),
                    TextRenderingHint = TextRenderingHint.SingleBitPerPixel,
                    SmoothingMode = SmoothingMode.None
                };

                pdfOptions.VectorRasterizationOptions = vectorOptions;

                // Save as PDF
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed scalable Windows Metafile graphics into a PDF report generated by a C# application.
 * 2. When converting legacy EMF diagrams to PDF for archival or sharing without losing vector quality.
 * 3. When generating PDF invoices that include EMF logos and require precise sizing and white background.
 * 4. When automating batch processing of EMF assets to PDF for a document management system using Aspose.Imaging.
 * 5. When creating PDF documentation from EMF technical drawings while controlling text rendering and smoothing settings.
 */
