// HOW-TO: Resize CorelDRAW CDR to 1024x768 PNG in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // All runtime errors are caught and reported.
        try
        {
            // Hard‑coded input and output file paths.
            string inputPath = "sample.cdr";
            string outputPath = "sample_resized.png";

            // Verify that the input file exists.
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists (creates it if necessary).
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");

            // Load the CorelDRAW (CDR) file.
            using (Image image = Image.Load(inputPath))
            {
                // Resize to the required dimensions.
                image.Resize(1024, 768);

                // Prepare PNG save options (default settings are sufficient here).
                var pngOptions = new PngOptions();

                // Save the resized image as PNG.
                image.Save(outputPath, pngOptions);
            }
        }
        catch (Exception ex)
        {
            // Report any unexpected errors without crashing.
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a desktop publishing workflow requires converting original CDR artwork into web‑ready PNG thumbnails of a fixed 1024×768 size.
 * 2. When an e‑commerce platform needs to generate product preview images from designers’ CorelDRAW files without manual resizing.
 * 3. When a batch‑processing service must automate the transformation of legacy CDR assets into PNGs for inclusion in a mobile app.
 * 4. When a reporting tool has to embed resized PNG versions of CDR diagrams into PDF or HTML reports generated by a C# application.
 * 5. When a cloud‑based image pipeline needs to standardize incoming CorelDRAW files to a specific resolution before further analysis or storage.
 */
