using System;
using System.IO;
using Aspose.Imaging.FileFormats.Dicom;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "input\\sample.dcm";
        string outputPath = "output\\sample_modified.dcm";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

        try
        {
            using (DicomImage dicomImage = (DicomImage)Aspose.Imaging.Image.Load(inputPath))
            {
                dicomImage.Save(outputPath);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a hospital IT system needs to embed patient‑specific XMP metadata into existing DICOM scans before archiving them in a PACS repository.
 * 2. When a research lab wants to programmatically annotate MRI images with study identifiers using C# and Aspose.Imaging while keeping the original DICOM pixel data intact.
 * 3. When a medical device manufacturer must add manufacturer‑defined XMP tags to CT images generated by the device before exporting them for regulatory submission.
 * 4. When a cloud‑based tele‑radiology platform needs to enrich incoming DICOM files with custom XMP metadata for indexing and then store the modified files back in DICOM format.
 * 5. When a healthcare analytics application requires batch processing of DICOM files to insert XMP metadata for later AI model training without altering image quality.
 */