using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.Sources;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputDirectory = Path.Combine(Directory.GetCurrentDirectory(), "Input");
            string outputDirectory = Path.Combine(Directory.GetCurrentDirectory(), "Output");

            // Ensure output directory exists
            Directory.CreateDirectory(outputDirectory);

            // Get all CDR files in the input directory
            string[] files = Directory.GetFiles(inputDirectory, "*.cdr");

            foreach (string inputPath in files)
            {
                // Validate input file existence
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                string fileNameWithoutExt = Path.GetFileNameWithoutExtension(inputPath);
                string outputPath = Path.Combine(outputDirectory, fileNameWithoutExt + ".bmp");

                // Ensure output directory exists for this file
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                using (Image image = Image.Load(inputPath))
                {
                    // Cast to CdrImage using fully qualified name
                    var cdrImage = image as Aspose.Imaging.FileFormats.Cdr.CdrImage;
                    if (cdrImage == null)
                    {
                        Console.Error.WriteLine($"Failed to load CDR image: {inputPath}");
                        continue;
                    }

                    // Configure BMP options with 24‑bit depth
                    using (BmpOptions bmpOptions = new BmpOptions())
                    {
                        bmpOptions.BitsPerPixel = 24;

                        // Set vector rasterization options for proper rendering
                        bmpOptions.VectorRasterizationOptions = new VectorRasterizationOptions
                        {
                            BackgroundColor = Color.White,
                            PageWidth = cdrImage.Width,
                            PageHeight = cdrImage.Height,
                            TextRenderingHint = TextRenderingHint.SingleBitPerPixel,
                            SmoothingMode = SmoothingMode.None
                        };

                        // Save the CDR page as BMP
                        cdrImage.Save(outputPath, bmpOptions);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a graphic design studio needs to automatically convert a folder of CorelDRAW (.cdr) artwork into 24‑bit BMP files for legacy Windows printing pipelines.
 * 2. When an e‑learning platform must batch‑process user‑uploaded CDR diagrams into BMP images to embed them in HTML5 course material without losing color fidelity.
 * 3. When a document management system requires nightly conversion of stored CDR vector files to BMP format for compatibility with third‑party OCR engines that only accept 24‑bit raster images.
 * 4. When a manufacturing company wants to generate high‑resolution BMP previews of CDR schematics for inclusion in PDF catalogs generated by an automated reporting tool.
 * 5. When a cloud‑based image‑conversion service needs to expose an API endpoint that transforms multiple CDR files to 24‑bit BMP in one operation using Aspose.Imaging for .NET.
 */