// HOW-TO: Convert EPS To TIFF In C# With Aspose.Imaging (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Tiff.Enums;

class Program
{
    static void Main()
    {
        // Hardcoded input and output file paths
        string inputPath = @"C:\temp\input.eps";
        string outputPath = @"C:\temp\output.tif";

        // Verify that the input file exists
        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        // Ensure the output directory exists
        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

        try
        {
            // Load the EPS image
            using (Image image = Image.Load(inputPath))
            {
                // Prepare TIFF save options (default format)
                var tiffOptions = new TiffOptions(TiffExpectedFormat.Default);

                // Save the image as TIFF
                image.Save(outputPath, tiffOptions);
            }
        }
        catch (Exception ex)
        {
            // Report any runtime errors
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to convert vector EPS artwork received from a designer into a high‑resolution TIFF for printing or archival in a .NET application.
 * 2. When a document processing system must ingest EPS files and store them as TIFF images to maintain compatibility with legacy imaging workflows.
 * 3. When an automated batch job has to transform EPS logos into TIFF format for inclusion in PDF reports generated by C# code.
 * 4. When a web service receives EPS uploads and must provide TIFF previews to users without using external tools.
 * 5. When a desktop utility needs to validate the existence of an EPS file and reliably save it as a TIFF using Aspose.Imaging for further image analysis.
 */
