using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Pdf;
using Aspose.Imaging.FileFormats.Eps;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output file paths
            string inputPath = @"C:\Images\Sample.eps";
            string outputPath = @"C:\Images\Sample.pdf";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load EPS image and cast to EpsImage
            using (var image = (EpsImage)Image.Load(inputPath))
            {
                // Prepare PDF export options with compliance setting
                var pdfOptions = new PdfOptions
                {
                    PdfCoreOptions = new PdfCoreOptions
                    {
                        PdfCompliance = PdfComplianceVersion.PdfA1b
                    }
                };

                // Save as PDF
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert a vector EPS artwork, such as a company logo, into a PDF file for high‑quality printing or distribution, this code provides a straightforward C# solution.
 * 2. When a web application must accept user‑uploaded EPS files and store them as PDF documents for archival compliance (e.g., PDF/A‑1b), the example demonstrates the required file‑format conversion.
 * 3. When an automated batch process has to generate PDF reports from EPS diagrams generated by CAD tools, the code shows how to load the EPS and save it directly as PDF using Aspose.Imaging.
 * 4. When a desktop utility must validate the existence of an EPS file, ensure the output folder exists, and then produce a PDF for viewing on devices that do not support EPS, this snippet handles all those steps.
 * 5. When a developer wants to enforce PDF compliance standards while converting EPS graphics to PDF in a .NET environment, the example illustrates setting PdfCoreOptions for PDF/A‑1b compliance during the export.
 */