using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Wrap the whole logic to catch unexpected exceptions
        try
        {
            // Hardcoded input and output file paths
            string inputPath = @"C:\Images\sample.emf";
            string outputPath = @"C:\Images\sample.pdf";

            // Verify that the input EMF file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists (creates it if necessary)
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the EMF image and save it as PDF
            using (Image image = Image.Load(inputPath))
            {
                // Use PdfOptions to specify PDF output format
                var pdfOptions = new PdfOptions();
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            // Report any runtime errors without crashing
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to embed a legacy Windows Metafile (EMF) diagram into a PDF report generated by a .NET application.
 * 2. When an automated document conversion service must transform vector‑based EMF assets into searchable PDF files for archival.
 * 3. When a desktop utility program has to verify the existence of an EMF logo file and export it as a high‑quality PDF for printing.
 * 4. When a batch processing script processes a folder of EMF icons and saves each as a PDF using Aspose.Imaging’s Image.Load and PdfOptions.
 * 5. When an error‑handling routine must safely load an EMF image, create missing output directories, and save the result as PDF without crashing the application.
 */