// HOW-TO: Merge Multiple EMF Files into a Single Vector PDF in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using System.Collections.Generic;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Define input EMF files (relative paths)
            List<string> emfFiles = new List<string>
            {
                "Input/file1.emf",
                "Input/file2.emf",
                "Input/file3.emf"
            };

            // Verify each input file exists
            foreach (string path in emfFiles)
            {
                if (!File.Exists(path))
                {
                    Console.Error.WriteLine($"File not found: {path}");
                    return;
                }
            }

            // Define output PDF path
            string outputPath = "Output/merged.pdf";

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Prepare vector rasterization options for each EMF page
            List<VectorRasterizationOptions> pageOptions = new List<VectorRasterizationOptions>();
            foreach (string path in emfFiles)
            {
                using (Aspose.Imaging.Image img = Aspose.Imaging.Image.Load(path))
                {
                    VectorRasterizationOptions vopt = new VectorRasterizationOptions
                    {
                        BackgroundColor = Aspose.Imaging.Color.White,
                        PageSize = img.Size,
                        TextRenderingHint = Aspose.Imaging.TextRenderingHint.SingleBitPerPixel,
                        SmoothingMode = Aspose.Imaging.SmoothingMode.None
                    };
                    pageOptions.Add(vopt);
                }
            }

            // Configure PDF options with multipage settings
            PdfOptions pdfOptions = new PdfOptions
            {
                MultiPageOptions = new MultiPageOptions
                {
                    PageRasterizationOptions = pageOptions.ToArray()
                }
            };

            // Load the first EMF image and save all pages to a single PDF
            using (Aspose.Imaging.Image firstImg = Aspose.Imaging.Image.Load(emfFiles[0]))
            {
                firstImg.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to combine several EMF diagrams generated by a reporting tool into one searchable PDF for distribution.
 * 2. When you want to preserve the original vector quality of EMF graphics while creating a multi‑page PDF for printing.
 * 3. When an application must batch‑process a folder of EMF assets and output a single PDF for archiving.
 * 4. When you need to programmatically generate a PDF portfolio that contains each EMF file as a separate page without rasterizing to bitmap.
 * 5. When you are building a C# service that converts legacy Windows Metafile images into a compact PDF document for web preview.
 */
