using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Jpeg;
using Aspose.Imaging.FileFormats.Pdf;
using Aspose.Imaging.Sources;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Hardcoded input EMF files
            string[] inputPaths = new string[]
            {
                @"C:\Images\first.emf",
                @"C:\Images\second.emf",
                @"C:\Images\third.emf"
            };

            // Hardcoded output PDF file
            string outputPath = @"C:\Images\MergedOutput.pdf";

            // Validate input files
            foreach (string inputPath in inputPaths)
            {
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Collect sizes of all EMF images
            List<Aspose.Imaging.Size> sizes = new List<Aspose.Imaging.Size>();
            foreach (string path in inputPaths)
            {
                using (Image img = Image.Load(path))
                {
                    sizes.Add(new Aspose.Imaging.Size(img.Width, img.Height));
                }
            }

            // Determine canvas size (stack vertically)
            int canvasWidth = sizes.Max(s => s.Width);
            int canvasHeight = sizes.Sum(s => s.Height);

            // Create a raster canvas (unbound) using JPEG options
            JpegOptions jpegOptions = new JpegOptions();
            using (RasterImage canvas = (RasterImage)Image.Create(jpegOptions, canvasWidth, canvasHeight))
            {
                int offsetY = 0;
                foreach (string path in inputPaths)
                {
                    using (Image img = Image.Load(path))
                    {
                        // Rasterize the vector EMF to raster pixels
                        using (RasterImage raster = (RasterImage)img)
                        {
                            Aspose.Imaging.Rectangle bounds = new Aspose.Imaging.Rectangle(0, offsetY, raster.Width, raster.Height);
                            canvas.SaveArgb32Pixels(bounds, raster.LoadArgb32Pixels(raster.Bounds));
                        }
                    }
                    offsetY += sizes.First(s => s.Width == Image.Load(path).Width && s.Height == Image.Load(path).Height).Height;
                }

                // Save the merged canvas as PDF
                PdfOptions pdfOptions = new PdfOptions();
                canvas.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to combine several vector‑based EMF diagrams generated by a CAD tool into one searchable PDF report using C# and Aspose.Imaging.
 * 2. When an application must programmatically create a multi‑page PDF portfolio of engineering schematics stored as EMF files while preserving their vector quality for printing.
 * 3. When a batch‑processing service has to merge daily exported EMF charts from a monitoring system into a single PDF document for archival and distribution.
 * 4. When a Windows desktop utility must concatenate multiple EMF logos into a single PDF brochure without rasterizing the graphics, using Aspose.Imaging’s image loading and PDF conversion features.
 * 5. When an automated document generation pipeline needs to stitch together EMF‑based flowcharts into one PDF file to embed in a larger PDF package, ensuring scalability and crispness of the vector elements.
 */