using System;
using System.IO;
using System.Collections.Generic;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Input EMF files (hardcoded)
            string[] inputPaths = new[]
            {
                "input1.emf",
                "input2.emf",
                "input3.emf"
            };

            // Output PDF file (hardcoded)
            string outputPath = "merged.pdf";

            // Validate each input file
            foreach (string inputPath in inputPaths)
            {
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }
            }

            // Ensure output directory exists
            string outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrWhiteSpace(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            // Load EMF images
            List<Image> images = new List<Image>();
            foreach (string inputPath in inputPaths)
            {
                Image img = Image.Load(inputPath);
                images.Add(img);
            }

            // Create a multipage image (PDF) from the loaded EMF images
            using (Image pdfImage = Image.Create(images.ToArray(), true))
            {
                PdfOptions pdfOptions = new PdfOptions();
                pdfImage.Save(outputPath, pdfOptions);
            }

            // Dispose loaded EMF images
            foreach (Image img in images)
            {
                img.Dispose();
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to combine several Windows Metafile (EMF) diagrams generated by a CAD tool into a single searchable PDF report using C# and Aspose.Imaging while preserving vector quality.
 * 2. When an application must programmatically assemble multiple EMF-based charts from a financial dashboard into a multipage PDF brochure for client distribution without rasterizing the graphics.
 * 3. When a document automation system has to merge EMF logos and icons from different modules into one PDF catalog, ensuring the images remain scalable and crisp on any device.
 * 4. When a batch processing script has to convert a collection of EMF print previews into a consolidated PDF portfolio for archival, using Aspose.Imaging’s Image.Create and PdfOptions in .NET.
 * 5. When a web service needs to accept several EMF files uploaded by users and return a single PDF file that retains the original vector data for high‑resolution printing.
 */