using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Tiff;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = @"C:\Images\multi_page.tif";
            string outputDir = @"C:\Images\SplitPages";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists (Directory.CreateDirectory handles null safely)
            Directory.CreateDirectory(outputDir);

            // Load the multi‑page TIFF
            using (TiffImage multiPage = (TiffImage)Image.Load(inputPath))
            {
                // Iterate through each frame
                for (int i = 0; i < multiPage.Frames.Length; i++)
                {
                    // Get the current frame
                    TiffFrame frame = multiPage.Frames[i];

                    // Create a new TiffImage containing only this frame
                    using (TiffImage singlePage = new TiffImage(frame))
                    {
                        // Build output file path
                        string outputPath = Path.Combine(outputDir, $"page_{i + 1}.tif");

                        // Ensure the directory for the output file exists
                        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                        // Save the single‑page TIFF (metadata is preserved within the frame)
                        singlePage.Save(outputPath);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to extract each scanned page from a multi‑page TIFF generated by a high‑speed scanner so that individual pages can be uploaded to a document management system while retaining EXIF and TIFF tags.
 * 2. When an application must separate each frame of a multi‑page medical imaging TIFF (e.g., DICOM‑converted) to feed them into separate analysis pipelines without losing patient metadata.
 * 3. When a web service processes batch‑uploaded multi‑page TIFF invoices and must create single‑page TIFF files for OCR engines that only accept one page per file, preserving the original resolution and metadata.
 * 4. When a digital archiving tool needs to split large multi‑page TIFF maps into individual tiles for GIS software, ensuring that geographic metadata embedded in each frame remains intact.
 * 5. When a developer builds a C# utility that prepares multi‑page TIFF comic books for e‑readers that require separate page files, using Aspose.Imaging to keep the original color profile and metadata for each page.
 */