// HOW-TO: Convert WebP Image to PDF in C# Using Aspose.Imaging (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "Input\\sample.webp";
            string outputPath = "Output\\sample.pdf";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                using (PdfOptions pdfOptions = new PdfOptions())
                {
                    image.Save(outputPath, pdfOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed a WebP graphic into a PDF report generated by a C# application.
 * 2. When an e‑commerce platform must convert user‑uploaded WebP product photos to PDF invoices on the server.
 * 3. When a document‑automation service has to transform WebP thumbnails stored as byte arrays into searchable PDF files.
 * 4. When a batch‑processing tool must programmatically convert a folder of WebP images to PDF for archival purposes.
 * 5. When a Windows desktop app requires on‑the‑fly conversion of WebP images to PDF without using intermediate files.
 */
