// HOW-TO: Convert WebP Image To PDF In C# Using Aspose.Imaging (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Pdf;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "Input\\sample.webp";
            string outputPath = "Output\\sample.pdf";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                PdfOptions pdfOptions = new PdfOptions();
                image.Save(outputPath, pdfOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed a WebP graphic into a PDF report generated by a C# application without writing intermediate files.
 * 2. When an e‑commerce platform must convert user‑uploaded WebP product photos to PDF invoices on the server side.
 * 3. When a document management system requires batch conversion of WebP assets to searchable PDF archives using Aspose.Imaging in .NET.
 * 4. When a mobile backend service receives WebP images as byte arrays and must return them as PDF thumbnails for email attachments.
 * 5. When a compliance tool must transform WebP screenshots into PDF evidence files while preserving image quality in a C# workflow.
 */
