// HOW-TO: Convert WebP Image to PDF Using Aspose.Imaging in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Webp;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Hardcoded input and output paths
        string inputPath = @"c:\temp\input.webp";
        string outputPath = @"c:\temp\output.pdf";

        try
        {
            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load WebP image and save as PDF
            using (WebPImage webPImage = new WebPImage(inputPath))
            {
                webPImage.Save(outputPath, new PdfOptions());
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed a WebP graphic into a PDF report generated by a .NET application.
 * 2. When a web service receives user‑uploaded WebP files and must deliver them as printable PDF documents.
 * 3. When automating batch conversion of WebP assets to PDF for archival or compliance purposes.
 * 4. When creating PDF invoices that include product images originally stored in WebP format.
 * 5. When integrating Aspose.Imaging into a document‑generation workflow that requires converting WebP logos to PDF for consistent branding.
 */
