// HOW-TO: Convert WebP Image to PDF Using Aspose.Imaging in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            string inputPath = "input.webp";
            string outputPath = "output.pdf";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                PdfOptions options = new PdfOptions();
                image.Save(outputPath, options);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed a WebP graphic into a PDF report generated by a C# application.
 * 2. When you want to provide customers a downloadable PDF version of a WebP logo without using external tools.
 * 3. When an automated workflow must transform WebP assets into PDF files for archival or printing purposes.
 * 4. When a web service receives WebP uploads and must return them as PDF documents for compliance.
 * 5. When you are building a batch converter that processes multiple WebP images into PDFs in a .NET environment.
 */
