// HOW-TO: Convert OTG Image To PNG In C# With Aspose.Imaging (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.Sources;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "Input\\image.otg";
            string outputPath = "Output\\image.png";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                PngOptions options = new PngOptions
                {
                    Source = new FileCreateSource(outputPath, false)
                };
                image.Save(outputPath, options);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert proprietary OTG graphics generated by CAD tools into widely supported PNG files for web display.
 * 2. When an automated batch process must read OTG images from a folder and export them as lossless PNGs for archival storage.
 * 3. When a .NET application has to embed OTG icons into a PDF and requires them in PNG format before insertion.
 * 4. When a server‑side service receives OTG uploads and must transform them to PNG to generate thumbnails for a gallery.
 * 5. When a migration script updates legacy OTG assets to PNG to ensure compatibility with modern image viewers and browsers.
 */
