using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Wrap the whole process in a try-catch to handle unexpected errors gracefully
        try
        {
            // Hardcoded input and output file paths
            string inputPath = @"C:\Images\sample.odg";
            string outputPath = @"C:\Images\output.bmp";

            // Verify that the input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists (creates it if necessary)
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the ODG image
            using (Image odgImage = Image.Load(inputPath))
            {
                // Prepare BMP saving options; default compression (Bitfields) preserves transparency
                BmpOptions bmpOptions = new BmpOptions();

                // Save the image as BMP preserving alpha channel
                odgImage.Save(outputPath, bmpOptions);
            }
        }
        catch (Exception ex)
        {
            // Output any error message without crashing the application
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a C# application must import OpenDocument Graphics (ODG) assets from a design team and render them as BMP files with alpha channel support for use in a Windows desktop UI.
 * 2. When an automated build pipeline needs to batch‑convert ODG diagrams to BMP images while preserving transparency for inclusion in PDF reports generated by .NET services.
 * 3. When a game development tool written in C# requires converting ODG icons to BMP format so that the engine can load them with proper transparency on legacy hardware.
 * 4. When a document management system has to store user‑uploaded ODG files as BMP thumbnails that retain transparent backgrounds for preview galleries.
 * 5. When a migration script must transform legacy ODG graphics into BMP files with alpha channels to maintain visual fidelity during a move to a new content management platform.
 */