using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Hardcoded input and output paths
        string inputPath = @"C:\Images\sample.otg";
        string outputPath = @"C:\Images\sample.svg";

        try
        {
            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the OTG image
            using (Image image = Image.Load(inputPath))
            {
                // Prepare SVG rasterization options with correct page size (sets viewBox)
                var svgRasterOptions = new SvgRasterizationOptions
                {
                    PageSize = image.Size
                };

                // Prepare SVG save options and assign rasterization options
                var svgOptions = new SvgOptions
                {
                    VectorRasterizationOptions = svgRasterOptions
                };

                // Save as SVG
                image.Save(outputPath, svgOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert legacy OTG vector graphics generated by older design tools into modern SVG files for web display, preserving the original dimensions via the viewBox attribute.
 * 2. When an automated image‑processing pipeline must batch‑convert OTG assets stored on a file server to scalable SVG format so that responsive UI components can render them without loss of quality.
 * 3. When a C# application integrates with a content‑management system that only accepts SVG uploads, requiring on‑the‑fly conversion of user‑provided OTG files while ensuring the SVG’s viewBox matches the original image size.
 * 4. When a developer is building a desktop utility that validates the existence of input OTG files, creates missing output directories, and saves the graphics as SVG with correct page size for downstream vector editing tools.
 * 5. When a reporting tool needs to embed vector diagrams originally saved as OTG into PDF or HTML reports, using Aspose.Imaging to rasterize them into SVG with an accurate viewBox for consistent scaling across browsers.
 */