// HOW-TO: Convert OTG to SVG with Layer Names Preserved in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

namespace OtgToSvgConverter
{
    class Program
    {
        static void Main()
        {
            string inputPath = "input.otg";
            string outputPath = "output.svg";

            try
            {
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                using (Image image = Image.Load(inputPath))
                {
                    var options = new SvgOptions();
                    image.Save(outputPath, options);
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to export a multi‑layer OTG design to a scalable SVG for web display while keeping the original layer names for later editing.
 * 2. When an automated build pipeline must convert OTG assets generated by a CAD tool into SVG files for inclusion in documentation or reports.
 * 3. When a desktop application processes user‑uploaded OTG files and must provide a vector‑based preview in SVG format without losing layer information.
 * 4. When migrating legacy OTG graphics to a modern vector format for responsive UI components, preserving layer hierarchy for CSS targeting.
 * 5. When integrating Aspose.Imaging into a C# service that batch‑converts OTG drawings to SVG to support third‑party vector editors that rely on layer names.
 */
