using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Bmp;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = @"C:\Images\sample.otg";
            string outputPath = @"C:\Images\sample_8bit.bmp";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the OTG image
            using (Image image = Image.Load(inputPath))
            {
                // Prepare BMP options with 8 bits per pixel
                BmpOptions bmpOptions = new BmpOptions
                {
                    BitsPerPixel = 8,
                    // Generate an 8‑bit palette that closely matches the source image
                    Palette = ColorPaletteHelper.GetCloseImagePalette((RasterImage)image, 256)
                };

                // Save the image as BMP using the specified options
                image.Save(outputPath, bmpOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert proprietary OTG graphics generated by a CAD system into a standard BMP file with an 8‑bit palette to embed the image in legacy Windows applications.
 * 2. When a batch image processing tool must shrink large OTG screenshots for faster network transfer by saving them as 256‑color BMP files using C# and Aspose.Imaging.
 * 3. When a game‑modding pipeline requires converting high‑color OTG textures to 8‑bit BMP assets to meet the memory constraints of an older game engine.
 * 4. When an automated report generator has to include OTG diagrams in printable documents and must reduce the file size by saving them as 8‑bit BMP images.
 * 5. When a cloud‑based service processes user‑uploaded OTG files and needs to store them as compact BMP files with a generated palette for archival purposes.
 */