// HOW-TO: Convert ODG File From Memory Stream To PNG In C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.OpenDocument;

class Program
{
    static void Main()
    {
        // Hardcoded input and output paths
        string inputPath = "sample.odg";
        string outputPath = "output.png";

        try
        {
            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load ODG file into a memory stream
            using (FileStream fileStream = File.OpenRead(inputPath))
            using (MemoryStream memoryStream = new MemoryStream())
            {
                fileStream.CopyTo(memoryStream);
                memoryStream.Position = 0; // Reset stream position

                // Load the image from the memory stream and cast to OdgImage
                using (Image img = Image.Load(memoryStream) as OdgImage)
                {
                    if (img == null)
                    {
                        Console.Error.WriteLine("Failed to load ODG image.");
                        return;
                    }

                    // Prepare PNG save options
                    PngOptions pngOptions = new PngOptions();

                    // Save the image as PNG
                    img.Save(outputPath, pngOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to display an OpenDocument graphic on a web page that only supports PNG images.
 * 2. When processing user‑uploaded ODG files in a server‑side C# service and storing them as PNG thumbnails.
 * 3. When converting legacy ODG diagrams to PNG for inclusion in PDF reports generated by .NET applications.
 * 4. When reading ODG data from a database BLOB into a memory stream and saving it as PNG for further processing.
 * 5. When automating batch conversion of ODG assets stored in cloud storage to PNG format using Aspose.Imaging.
 */
