// HOW-TO: Convert Embedded ODG Resource to PNG File in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using System.Reflection;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

namespace OdgToPngConverter
{
    class Program
    {
        static void Main()
        {
            try
            {
                // Output path (hard‑coded)
                string outputPath = "converted.png";

                // Ensure the output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? string.Empty);

                // Embedded resource name (hard‑coded)
                string resourceName = "OdgToPngConverter.Resources.sample.odg";

                Assembly assembly = Assembly.GetExecutingAssembly();
                using (Stream resourceStream = assembly.GetManifestResourceStream(resourceName))
                {
                    if (resourceStream == null)
                    {
                        Console.Error.WriteLine($"Embedded resource not found: {resourceName}");
                        return;
                    }

                    using (Image image = Image.Load(resourceStream))
                    {
                        var pngOptions = new PngOptions();
                        image.Save(outputPath, pngOptions);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to display an OpenDocument graphic stored inside your assembly as a PNG on a web page.
 * 2. When you want to generate thumbnail previews of ODG diagrams packaged as embedded resources in a desktop application.
 * 3. When you must convert vector‑based ODG assets to raster PNG files for inclusion in PDF reports generated by C# code.
 * 4. When you are building a localization pipeline that extracts ODG icons from resources and saves them as PNGs for mobile platforms.
 * 5. When you need to automate batch conversion of embedded ODG drawings to PNG during a CI build to verify visual assets.
 */
