using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = @"C:\Images\sample.otg";
            string outputPath = @"C:\Images\output.png";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the OTG image and ensure proper disposal
            using (Image image = Image.Load(inputPath))
            {
                // Configure rasterization options to match the source size
                var otgRasterizationOptions = new OtgRasterizationOptions
                {
                    PageSize = image.Size
                };

                // Set up PNG save options with the rasterization options
                var pngOptions = new PngOptions
                {
                    VectorRasterizationOptions = otgRasterizationOptions
                };

                // Save the image as PNG
                image.Save(outputPath, pngOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a .NET application must convert proprietary OTG vector graphics generated by CAD tools into PNG raster images for web display, ensuring resources are released with a using block.
 * 2. When an automated image‑processing pipeline needs to batch‑convert OTG files stored on a server to PNG thumbnails while guaranteeing proper disposal of the Image object.
 * 3. When a Windows service reads OTG diagrams uploaded by users and saves them as PNG files for inclusion in PDF reports, using a using statement to prevent memory leaks.
 * 4. When a desktop utility provides a drag‑and‑drop feature that transforms OTG drawings into PNG assets for game development, wrapping the load operation in a using block for safe cleanup.
 * 5. When a cloud‑based C# microservice receives OTG files via API, converts them to PNG for downstream image‑analysis services, and must ensure the Image instance is disposed promptly.
 */