// HOW-TO: Convert Single Page CMX to TIFF with Default Compression in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging.FileFormats.Cmx;
using Aspose.Imaging.FileFormats.Tiff.Enums;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "Input\\image.cmx";
        string outputPath = "Output\\image.tiff";

        try
        {
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (CmxImage cmx = (CmxImage)Aspose.Imaging.Image.Load(inputPath))
            {
                TiffOptions tiffOptions = new TiffOptions(TiffExpectedFormat.Default);
                cmx.Save(outputPath, tiffOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to archive a CMX vector drawing as a lossless TIFF for long‑term storage.
 * 2. When a printing workflow requires TIFF images but the source files are supplied in CMX format.
 * 3. When integrating legacy CorelDRAW CMX assets into a .NET application that only processes TIFF files.
 * 4. When converting a single‑page CMX diagram to a TIFF to embed it in a PDF report generated by C# code.
 * 5. When automating batch conversion of CMX drawings to TIFF for compatibility with image‑processing libraries that expect TIFF input.
 */
