using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.MagicWand;
using Aspose.Imaging.MagicWand.ImageMasks;
using Aspose.Imaging.FileFormats.Tiff.Enums;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "input.tif";
            string outputPath = "output.tif";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (RasterImage image = (RasterImage)Image.Load(inputPath))
            {
                int centerX = image.Width / 2;
                int centerY = image.Height / 2;

                MagicWandTool.Select(image, new MagicWandSettings(centerX, centerY))
                    .GetFeathered(new FeatheringSettings { Size = 5 })
                    .Apply();

                var tiffOptions = new TiffOptions(TiffExpectedFormat.Default);
                image.Save(outputPath, tiffOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to smooth the edges of a selection mask on a high‑resolution TIFF photograph before saving it, they can use GetFeathered with a 5‑pixel radius to create a soft transition.
 * 2. When preparing scanned documents for OCR, a developer may apply a 5‑pixel feather to the mask generated by MagicWand to reduce harsh borders that could interfere with text recognition.
 * 3. When generating print‑ready artwork from a large TIFF image, a developer can feather the mask edges by 5 pixels to avoid visible seams when the masked region is overlaid on other graphics.
 * 4. When building a web service that receives TIFF images and needs to automatically isolate and smooth a central object, a developer can use the MagicWandTool with GetFeathered(5) to produce a clean, anti‑aliased mask.
 * 5. When creating a batch‑processing pipeline for archival TIFF files, a developer can incorporate a 5‑pixel feathering step to ensure consistent edge smoothing across all masked images before they are stored.
 */