using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.Sources;
using Aspose.Imaging.MagicWand;
using Aspose.Imaging.MagicWand.ImageMasks;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "test_input.png";
        string outputPath = "output/union_result.png";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

        try
        {
            using (RasterImage image = (RasterImage)Image.Load(inputPath))
            {
                var mask1 = new RectangleMask(10, 10, 100, 100);
                var mask2 = new RectangleMask(50, 50, 100, 100);
                var unionMask = mask1.Union(mask2);

                bool insideBoth = unionMask.IsOpaque(60, 60);
                bool insideMask1Only = unionMask.IsOpaque(20, 20);
                bool insideMask2Only = unionMask.IsOpaque(120, 120);
                bool outsideBoth = unionMask.IsOpaque(200, 200);

                if (insideBoth && insideMask1Only && insideMask2Only && !outsideBoth)
                {
                    Console.WriteLine("Union mask verification passed.");
                }
                else
                {
                    Console.WriteLine("Union mask verification failed.");
                }

                unionMask.ApplyTo(image);
                var saveOptions = new PngOptions { Source = new FileCreateSource(outputPath, false) };
                image.Save(outputPath, saveOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. A developer merges two overlapping RectangleMask objects with Union to create a single mask that can be applied as a watermark region on a PNG image.
 * 2. When performing image analysis, a developer uses Union to combine multiple detected object masks into one region of interest for pixel filtering in a RasterImage.
 * 3. A developer creates a composite clipping path by uniting overlapping masks before saving the masked image as a PNG for web graphics.
 * 4. During unit testing, a developer verifies that the Union operation correctly marks pixels inside either original mask using IsOpaque, ensuring reliable image processing logic.
 * 5. In batch processing, a developer applies a unified mask generated by Union to many input PNG files to achieve consistent cropping or highlighting across the dataset.
 */