// HOW-TO: Remove PNG Watermark Using Telea Algorithm in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.Shapes;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "input.png";
        string outputPath = "output.png";

        try
        {
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (var image = Image.Load(inputPath))
            {
                var raster = (RasterImage)image;

                var mask = new GraphicsPath();
                var figure = new Figure();
                figure.AddShape(new EllipseShape(new RectangleF(50, 50, 200, 100)));
                mask.AddFigure(figure);

                var options = new Aspose.Imaging.Watermark.Options.TeleaWatermarkOptions(mask);

                using (var result = Aspose.Imaging.Watermark.WatermarkRemover.PaintOver(raster, options))
                {
                    result.Save(outputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to automatically erase a logo or watermark from product photos stored as PNG files before publishing them on an online store.
 * 2. When you must clean up scanned PNG images that contain a semi‑transparent watermark before performing OCR or further image analysis.
 * 3. When you want to programmatically remove a watermark from PNG screenshots generated by a reporting tool to create unbranded versions for internal use.
 * 4. When you are preparing PNG assets for a mobile app and need to strip out test watermarks added during the design phase without manual editing.
 * 5. When you need to batch‑process PNG graphics that contain elliptical watermarks, using the Telea inpainting algorithm to preserve surrounding visual details.
 */
