// HOW-TO: Convert SVG to BMP in ASP.NET Core Controller Using Aspose.Imaging (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

namespace MyApp
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                string inputPath = Path.Combine(Directory.GetCurrentDirectory(), "Input", "sample.svg");
                string outputPath = Path.Combine(Directory.GetCurrentDirectory(), "Output", "sample.bmp");

                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                using (Image image = Image.Load(inputPath))
                {
                    using (BmpOptions bmpOptions = new BmpOptions())
                    {
                        image.Save(outputPath, bmpOptions);
                    }
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to serve dynamically generated bitmap thumbnails from user‑uploaded SVG graphics in a web API.
 * 2. When a legacy Windows application requires BMP images but the source assets are stored as scalable SVG files.
 * 3. When you want to convert vector logos to raster BMP format for printing or embedding in PDF reports generated by an ASP.NET Core service.
 * 4. When you must provide BMP downloads for SVG diagrams to clients that only support bitmap formats in a web portal.
 * 5. When you are building an image processing pipeline that normalizes various vector formats to BMP before applying pixel‑based analysis in C#.
 */
