using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "input.emf";
            string outputPath = "output.png";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                var options = new PngOptions
                {
                    VectorRasterizationOptions = new VectorRasterizationOptions
                    {
                        BackgroundColor = Color.White,
                        PageWidth = image.Width,
                        PageHeight = image.Height,
                        TextRenderingHint = TextRenderingHint.SingleBitPerPixel,
                        SmoothingMode = SmoothingMode.None
                    }
                };

                image.Save(outputPath, options);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to extract each page of a multi‑page EMF (Enhanced Metafile) document and save them as separate PNG images for web preview or thumbnail generation.
 * 2. When converting vector‑based EMF reports generated by a reporting engine into raster PNG files to embed in email attachments or PDF reports.
 * 3. When automating the migration of legacy Windows Metafile graphics to modern PNG assets for a cross‑platform mobile app using C# and Aspose.Imaging.
 * 4. When creating a batch process that rasterizes each page of a multi‑page EMF blueprint into high‑resolution PNG files for printing or GIS integration.
 * 5. When building a document conversion service that receives EMF files via an API and returns a series of PNG images, one per page, using Aspose.Imaging’s VectorRasterizationOptions in .NET.
 */