using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging;

class Program
{
    static void Main()
    {
        // Wrap the whole logic in a try-catch to handle unexpected errors gracefully
        try
        {
            // Hardcoded input and output file paths
            string inputPath = @"C:\Images\input.emf";
            string outputPath = @"C:\Images\output.png";

            // Verify that the input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the EMF image
            using (Image image = Image.Load(inputPath))
            {
                // Configure rasterization options with anti‑aliasing for smoother edges
                var rasterOptions = new EmfRasterizationOptions
                {
                    PageSize = image.Size,
                    SmoothingMode = SmoothingMode.AntiAlias,
                    TextRenderingHint = TextRenderingHint.AntiAliasGridFit
                };

                // Set up PNG save options and attach the rasterization settings
                var pngOptions = new PngOptions
                {
                    VectorRasterizationOptions = rasterOptions
                };

                // Save the rasterized image as PNG
                image.Save(outputPath, pngOptions);
            }
        }
        catch (Exception ex)
        {
            // Output any error messages without crashing the program
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a Windows desktop application needs to export vector‑based EMF diagrams as high‑quality PNG thumbnails for display in a file‑browser UI.
 * 2. When a reporting service must convert EMF charts generated by Office into PNG images with anti‑aliasing to embed in PDF or HTML reports.
 * 3. When a batch‑processing tool has to rasterize a large collection of EMF icons into PNG assets for a mobile app, ensuring smooth edges through SmoothingMode.AntiAlias.
 * 4. When a document‑management system requires on‑the‑fly conversion of uploaded EMF files to PNG previews while preserving text clarity using TextRenderingHint.AntiAliasGridFit.
 * 5. When a C# automation script needs to generate PNG snapshots of EMF drawings for email notifications, applying anti‑aliasing to improve visual fidelity across different email clients.
 */