// HOW-TO: Convert EMF Stream to LZW Compressed TIFF in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Emf;
using Aspose.Imaging.FileFormats.Tiff.Enums;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Output TIFF file path
            string outputPath = "output.tif";

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Placeholder EMF data; replace with actual EMF byte array as needed
            byte[] emfData = new byte[] { /* EMF binary data */ };

            using (MemoryStream ms = new MemoryStream(emfData))
            {
                using (Image image = Image.Load(ms))
                {
                    // Cast the loaded image to EmfImage
                    EmfImage emfImage = (EmfImage)image;

                    // Configure TIFF options with LZW compression
                    TiffOptions tiffOptions = new TiffOptions(TiffExpectedFormat.TiffLzwRgb);
                    tiffOptions.Compression = TiffCompressions.Lzw;

                    // Set vector rasterization options for proper rendering
                    EmfRasterizationOptions rasterOptions = new EmfRasterizationOptions
                    {
                        PageSize = emfImage.Size,
                        BackgroundColor = Color.White
                    };
                    tiffOptions.VectorRasterizationOptions = rasterOptions;

                    // Save the EMF image as a TIFF file
                    emfImage.Save(outputPath, tiffOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed vector graphics from a Windows Metafile into a document that only accepts TIFF images with lossless LZW compression.
 * 2. When a reporting system receives EMF data as a byte array and must store it as a high‑quality TIFF for archival.
 * 3. When converting EMF charts generated by a legacy application into TIFF for printing on devices that require raster images.
 * 4. When processing scanned forms that are stored as EMF streams and you need to compress them into TIFF to reduce file size while preserving detail.
 * 5. When a web service receives EMF images via API and must return them as LZW‑compressed TIFF files for downstream image‑processing pipelines.
 */
