using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Wmf;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Hardcoded input and output paths
        string inputPath = @"C:\Images\sample.wmf";
        string outputPath = @"C:\Images\sample_resized.png";

        try
        {
            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load WMF image, resize, and save as PNG
            using (WmfImage wmfImage = (WmfImage)Image.Load(inputPath))
            {
                // Resize to 800x800 pixels
                wmfImage.Resize(800, 800);

                // Save as PNG with default options
                wmfImage.Save(outputPath, new PngOptions());
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to convert legacy WMF vector graphics to web‑friendly PNG files with a fixed 800 × 800 pixel size for consistent display in browsers.
 * 2. When an automated batch job must resize scanned WMF diagrams to 800 × 800 pixels before embedding them into PDF reports generated by a .NET application.
 * 3. When a Windows desktop application requires on‑the‑fly conversion of user‑uploaded WMF icons to 800 × 800 PNG thumbnails for a gallery view.
 * 4. When a content management system needs to standardize all WMF assets to a uniform 800 × 800 PNG resolution to meet mobile device bandwidth constraints.
 * 5. When a migration script moves legacy WMF assets from a file server to a cloud storage bucket, resizing each image to 800 × 800 pixels and saving as PNG to ensure compatibility with modern image pipelines.
 */