using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Wmf;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output directories
            string inputDir = @"C:\InputWmf";
            string outputDir = @"C:\OutputSvg";

            // Ensure the output directory exists
            Directory.CreateDirectory(outputDir);

            // Process each WMF file in the input directory
            foreach (string filePath in Directory.GetFiles(inputDir, "*.wmf"))
            {
                string inputPath = filePath;
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Determine output SVG path
                string fileNameWithoutExt = Path.GetFileNameWithoutExtension(inputPath);
                string outputPath = Path.Combine(outputDir, fileNameWithoutExt + ".svg");

                // Ensure the directory for the output file exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                // Load the WMF image
                using (WmfImage wmfImage = (WmfImage)Image.Load(inputPath))
                {
                    // Set up SVG save options
                    SvgOptions saveOptions = new SvgOptions
                    {
                        TextAsShapes = true
                    };

                    // Configure rasterization options with a uniform fill color (e.g., LightBlue)
                    WmfRasterizationOptions rasterizationOptions = new WmfRasterizationOptions
                    {
                        BackgroundColor = Aspose.Imaging.Color.LightBlue,
                        PageSize = wmfImage.Size,
                        RenderMode = Aspose.Imaging.FileFormats.Wmf.WmfRenderMode.Auto
                    };

                    saveOptions.VectorRasterizationOptions = rasterizationOptions;

                    // Save as SVG
                    wmfImage.Save(outputPath, saveOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to migrate a legacy Windows Metafile (WMF) icon set to scalable SVG graphics for a modern web UI while applying a consistent background fill color.
 * 2. When an automation script must convert dozens of WMF diagrams generated by an engineering tool into SVG files for inclusion in documentation, ensuring all shapes share the same fill color.
 * 3. When a batch image‑processing pipeline has to standardize the appearance of corporate branding assets by recoloring WMF logos to a brand‑specified LightBlue before exporting them as SVG.
 * 4. When a C# application must prepare printable vector assets by rasterizing WMF files with a uniform background and saving them as SVG for downstream design tools.
 * 5. When a developer is building a migration utility that scans a folder of WMF files, converts each to SVG, and enforces a single fill color to maintain visual consistency across a digital catalog.
 */