using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output directories
            string inputDirectory = @"C:\InputEmf";
            string outputDirectory = @"C:\OutputPng";

            // Get all EMF files in the input directory
            string[] emfFiles = Directory.GetFiles(inputDirectory, "*.emf");

            foreach (string inputPath in emfFiles)
            {
                // Verify input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Prepare output path with .png extension
                string outputPath = Path.Combine(outputDirectory, Path.GetFileNameWithoutExtension(inputPath) + ".png");

                // Ensure output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                // Load the EMF image
                using (Image image = Image.Load(inputPath))
                {
                    // Set up rasterization options with a uniform background color
                    EmfRasterizationOptions rasterOptions = new EmfRasterizationOptions
                    {
                        BackgroundColor = Aspose.Imaging.Color.LightGray,
                        PageSize = image.Size
                    };

                    // Configure PNG save options
                    PngOptions pngOptions = new PngOptions
                    {
                        VectorRasterizationOptions = rasterOptions
                    };

                    // Save the image as PNG
                    image.Save(outputPath, pngOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to migrate a legacy collection of EMF vector graphics to web‑friendly PNG files while ensuring a consistent background color across all images.
 * 2. When an automated build process must generate thumbnail PNG previews of EMF diagrams stored in a folder for inclusion in documentation portals.
 * 3. When a batch conversion tool is required to prepare EMF icons for a Windows desktop application that only supports raster PNG assets with a uniform light‑gray backdrop.
 * 4. When a server‑side C# service has to process user‑uploaded EMF files and store them as PNGs in a separate directory for downstream image analysis pipelines.
 * 5. When a migration script must convert EMF reports generated by older reporting tools into PNG format for archival in a content management system, preserving page size and applying a standard background color.
 */