using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Wmf;
using Aspose.Imaging.FileFormats.Png;

class Program
{
    static void Main()
    {
        // Hardcoded input folder containing WMF files
        string inputFolder = @"C:\Images\WmfInput";
        // Hardcoded output folder for PNG files
        string outputFolder = @"C:\Images\PngOutput";

        try
        {
            // Get all WMF files in the input folder
            string[] wmfFiles = Directory.GetFiles(inputFolder, "*.wmf");

            foreach (string inputPath in wmfFiles)
            {
                // Verify input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Determine output path with .png extension
                string fileNameWithoutExt = Path.GetFileNameWithoutExtension(inputPath);
                string outputPath = Path.Combine(outputFolder, fileNameWithoutExt + ".png");

                // Ensure output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                // Load WMF image
                using (Image image = Image.Load(inputPath))
                {
                    // Cast to WmfImage to access size
                    WmfImage wmfImage = (WmfImage)image;

                    // Set rasterization options for transparent background
                    var rasterOptions = new WmfRasterizationOptions
                    {
                        PageSize = wmfImage.Size,
                        BackgroundColor = Color.Transparent
                    };

                    // Configure PNG options: 32‑bit (Truecolor with Alpha) and vector rasterization
                    var pngOptions = new PngOptions
                    {
                        ColorType = PngColorType.TruecolorWithAlpha,
                        VectorRasterizationOptions = rasterOptions
                    };

                    // Save as PNG
                    image.Save(outputPath, pngOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to migrate a legacy library of Windows Metafile (WMF) icons into web‑ready PNG assets with transparent backgrounds for use in responsive UI designs.
 * 2. When an automated build pipeline must batch convert WMF diagrams generated by a reporting tool into 32‑bit PNG files so they render correctly on high‑DPI monitors.
 * 3. When a document management system requires extracting vector graphics from WMF files and storing them as lossless PNG images with an alpha channel for preview thumbnails.
 * 4. When a game development studio wants to preprocess WMF sprite sheets into PNG sprites with transparent backgrounds to integrate them into Unity or Unreal Engine pipelines.
 * 5. When a marketing automation script needs to bulk convert WMF logos into PNG format with truecolor and alpha support for inclusion in email newsletters and social media posts.
 */