// HOW-TO: Merge Multiple EPS Files into a Single PDF with Bookmarks in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Pdf;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Define input and output directories
            string baseDir = Directory.GetCurrentDirectory();
            string inputDirectory = Path.Combine(baseDir, "Input");
            string outputDirectory = Path.Combine(baseDir, "Output");

            // Ensure input directory exists
            if (!Directory.Exists(inputDirectory))
            {
                Directory.CreateDirectory(inputDirectory);
                Console.WriteLine($"Input directory created at: {inputDirectory}. Add files and rerun.");
                return;
            }

            // Ensure output directory exists
            if (!Directory.Exists(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            // Get all EPS files in the input directory
            string[] files = Directory.GetFiles(inputDirectory, "*.eps");

            var images = new List<Image>();

            // Load each EPS file
            foreach (var file in files)
            {
                if (!File.Exists(file))
                {
                    Console.Error.WriteLine($"File not found: {file}");
                    return;
                }
                var img = Image.Load(file);
                images.Add(img);
            }

            // Create a multipage image from the loaded EPS images
            using (Image result = Image.Create(images.ToArray(), true))
            {
                string outputPath = Path.Combine(outputDirectory, "Combined.pdf");
                // Ensure the output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                var pdfOptions = new PdfOptions();
                // Note: Adding bookmarks is not directly supported via Aspose.Imaging API.
                result.Save(outputPath, pdfOptions);
            }

            // Dispose individual images
            foreach (var img in images)
            {
                img.Dispose();
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a designer needs to combine several EPS logos into one PDF portfolio with a bookmark for each logo for easy navigation.
 * 2. When an automated publishing pipeline must convert a batch of EPS illustrations into a single searchable PDF document for distribution.
 * 3. When a reporting tool has to merge EPS charts generated by a graphics engine into a multi‑page PDF report with page‑level bookmarks.
 * 4. When an archival system requires consolidating EPS technical drawings into a single PDF file while preserving individual drawing titles as bookmarks.
 * 5. When a web service creates printable invoices that include EPS watermarks and needs to output a combined PDF with bookmarks for each invoice page.
 */
