using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.Sources;

class Program
{
    static void Main(string[] args)
    {
        string outputPath = @"c:\temp\venn.bmp";

        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            BmpOptions bmpOptions = new BmpOptions();
            bmpOptions.BitsPerPixel = 24;
            bmpOptions.Source = new FileCreateSource(outputPath, false);

            using (Image image = Image.Create(bmpOptions, 500, 500))
            {
                Graphics graphics = new Graphics(image);
                graphics.Clear(Color.White);

                // First ellipse (red)
                Pen redPen = new Pen(Color.Red, 2);
                graphics.DrawEllipse(redPen, new Rectangle(50, 150, 200, 200));

                // Second ellipse (green)
                Pen greenPen = new Pen(Color.Green, 2);
                graphics.DrawEllipse(greenPen, new Rectangle(150, 150, 200, 200));

                // Third ellipse (blue)
                Pen bluePen = new Pen(Color.Blue, 2);
                graphics.DrawEllipse(bluePen, new Rectangle(100, 50, 200, 200));

                image.Save();
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to generate a 24‑bit BMP file that visualizes overlapping data sets as a Venn diagram for a Windows desktop reporting tool.
 * 2. When an application must programmatically create a 500 × 500 pixel image with colored ellipses to illustrate set intersections in an e‑learning module.
 * 3. When a C# service creates printable diagram assets in BMP format for inclusion in PDF reports generated by a business intelligence system.
 * 4. When a developer wants to automate the production of simple vector‑style graphics, such as colored ellipses, without using external design software, by leveraging Aspose.Imaging’s Graphics API.
 * 5. When a legacy system requires BMP images with specific dimensions and colored outlines to be displayed on low‑resolution hardware screens that only support 24‑bit BMP files.
 */