using System;
using System.IO;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.Sources;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Output file path (hardcoded)
            string outputPath = @"C:\temp\output.bmp";

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Set BMP creation options
            BmpOptions bmpOptions = new BmpOptions();
            bmpOptions.BitsPerPixel = 24;
            bmpOptions.Source = new FileCreateSource(outputPath, false);

            // Create the image canvas
            using (Aspose.Imaging.Image image = Aspose.Imaging.Image.Create(bmpOptions, 400, 300))
            {
                // Initialize graphics for drawing
                Aspose.Imaging.Graphics graphics = new Aspose.Imaging.Graphics(image);

                // Create a thick green pen
                Aspose.Imaging.Pen pen = new Aspose.Imaging.Pen(Aspose.Imaging.Color.Green, 10);

                // Draw the ellipse
                graphics.DrawEllipse(pen, new Aspose.Imaging.Rectangle(50, 50, 300, 200));

                // Save the image to the file (already bound via FileCreateSource)
                image.Save();

                // Export the image as a byte array
                using (MemoryStream ms = new MemoryStream())
                {
                    // Save to stream using BMP options
                    image.Save(ms, new BmpOptions());

                    byte[] imageBytes = ms.ToArray();

                    // Example usage: write the byte array length to console
                    Console.WriteLine($"Image byte array length: {imageBytes.Length}");
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a desktop application needs to generate a BMP thumbnail with a highlighted green ellipse for a document preview and send the image as a byte array over a network.
 * 2. When an automated reporting tool must create a 24‑bit BMP chart, draw a thick green ellipse to emphasize a data region, and embed the resulting byte array into a PDF report.
 * 3. When a game engine requires runtime generation of a BMP sprite with a green elliptical border and needs the pixel data as a byte array for texture streaming.
 * 4. When a web service processes user‑uploaded images, creates a BMP placeholder with a green ellipse, and returns the image bytes to the client for immediate display.
 * 5. When a testing framework validates image‑processing pipelines by programmatically producing a BMP file with a green ellipse and comparing the generated byte array against expected results.
 */