using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.Brushes;
using Aspose.Imaging.FileFormats.Bmp;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded output path
            string outputPath = "C:\\temp\\output.bmp";

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Create a 200 × 200 BMP image
            using (BmpImage bmpImage = new BmpImage(200, 200))
            {
                // Fill the entire image with red
                Graphics graphics = new Graphics(bmpImage);
                SolidBrush redBrush = new SolidBrush(Color.Red);
                graphics.FillRectangle(redBrush, bmpImage.Bounds);

                // Save the image
                bmpImage.Save(outputPath);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to generate a simple 200 × 200 BMP thumbnail with a solid red background for a Windows desktop application using Aspose.Imaging for .NET.
 * 2. When an automated reporting tool must create a red placeholder BMP image of fixed dimensions to embed in PDF or Word documents generated by C# code.
 * 3. When a game asset pipeline requires a quick way to produce a red BMP texture of 200 × 200 pixels for testing rendering pipelines in Unity via C# scripts.
 * 4. When a web service that processes image uploads needs to return a default red BMP image of 200 × 200 pixels when the original file is missing or corrupted.
 * 5. When a batch job creates a series of red BMP markers of 200 × 200 size to be used as visual cues in a medical imaging workflow built with Aspose.Imaging and C#.
 */