using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.Sources;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Output BMP file path (hard‑coded)
            string outputPath = @"C:\temp\gauge.bmp";

            // Ensure the output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Create a file source bound to the output path
            Source fileSource = new FileCreateSource(outputPath, false);

            // Configure BMP options with the file source
            BmpOptions bmpOptions = new BmpOptions();
            bmpOptions.Source = fileSource;

            // Define canvas size (width x height)
            int canvasWidth = 400;
            int canvasHeight = 200;

            // Create the BMP canvas (output is already bound to the file source)
            using (RasterImage canvas = (RasterImage)Image.Create(bmpOptions, canvasWidth, canvasHeight))
            {
                // Initialize graphics for drawing
                Graphics graphics = new Graphics(canvas);

                // Clear background to white
                graphics.Clear(Color.White);

                // Define pens for arcs
                Pen outerPen = new Pen(Color.Black, 4);
                Pen innerPen = new Pen(Color.Gray, 2);
                Pen tickPen = new Pen(Color.DarkBlue, 1);

                // Draw outer semi‑circular arc (full gauge outline)
                // Rectangle defines the bounding ellipse; start at 180°, sweep -180° to draw the top half
                graphics.DrawArc(outerPen, new Rectangle(10, 10, canvasWidth - 20, canvasWidth - 20), 180, -180);

                // Draw inner semi‑circular arc (inner boundary)
                graphics.DrawArc(innerPen, new Rectangle(30, 30, canvasWidth - 60, canvasWidth - 60), 180, -180);

                // Draw tick marks as short arcs along the gauge
                int tickCount = 10;
                for (int i = 0; i <= tickCount; i++)
                {
                    // Calculate angle for each tick (evenly spaced across 180°)
                    float angle = 180f - (i * 180f / tickCount);
                    // Small arc length for tick (5° sweep)
                    graphics.DrawArc(tickPen, new Rectangle(50, 50, canvasWidth - 100, canvasWidth - 100), angle, -5);
                }

                // Save the bound image (no path needed)
                canvas.Save();
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to generate a BMP image of a semi‑circular gauge for an industrial equipment dashboard using C# and Aspose.Imaging.
 * 2. When a developer wants to create a lightweight BMP file that visualizes speedometer‑style tick marks for an automotive telemetry system.
 * 3. When a developer must produce a printable BMP gauge indicator for a medical device manual that requires precise arc drawing and custom pen colors.
 * 4. When a developer is building a Windows Forms application that dynamically renders a BMP gauge overlay to show real‑time sensor values without relying on external graphics libraries.
 * 5. When a developer needs to export a BMP gauge diagram with outer and inner arcs for inclusion in a PDF report generated by a .NET reporting tool.
 */