using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Emf;
using Aspose.Imaging.FileFormats.Emf.Graphics;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Hardcoded input and output paths
            string inputPath = "input.emf";
            string outputPath = "output.emf";

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the vector drawing
            using (Image image = Image.Load(inputPath))
            {
                // Cast to EmfImage
                EmfImage emfImage = (EmfImage)image;

                // Create a recorder from the existing EMF to flatten layers
                EmfRecorderGraphics2D graphics = EmfRecorderGraphics2D.FromEmfImage(emfImage);

                // End recording to obtain a flattened EMF image
                using (EmfImage flattened = graphics.EndRecording())
                {
                    // Save the flattened image as EMF
                    flattened.Save(outputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to merge multiple layers of a complex EMF vector drawing into a single layer before embedding it into a Word document to ensure consistent rendering across platforms.
 * 2. When an application must convert a multi‑layered EMF chart generated by a reporting tool into a flattened EMF file for faster loading in a legacy Windows Forms viewer.
 * 3. When a CAD integration service has to simplify a layered EMF blueprint by flattening it to reduce file size and improve printing performance.
 * 4. When a batch‑processing script must prepare EMF logos with separate text and shape layers for use in a corporate branding pipeline that only accepts single‑layer EMF assets.
 * 5. When a developer is building a migration utility that reads existing EMF files, flattens their layers, and saves the result to maintain visual fidelity after moving to a new document management system.
 */