using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Hardcoded input and output paths
        string inputPath = @"C:\Temp\input.svg";
        string outputPath = @"C:\Temp\output_optimized.svg";

        try
        {
            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the SVG image
            using (Image image = Image.Load(inputPath))
            {
                // Prepare rasterization options (required for SVG export)
                var rasterizationOptions = new SvgRasterizationOptions
                {
                    PageSize = image.Size
                };

                // Prepare SVG save options (no compression, keep default settings)
                var svgOptions = new SvgOptions
                {
                    VectorRasterizationOptions = rasterizationOptions,
                    Compress = false
                };

                // Save the optimized SVG
                image.Save(outputPath, svgOptions);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a web developer needs to shrink large SVG icons before uploading them to a website to improve page load speed, they can use this code to load the SVG, simplify its path data, and save an optimized version.
 * 2. When a mobile app team wants to ensure vector assets fit the device screen dimensions without extra processing, they can run this C# routine to rasterize the SVG to the image size and export a lightweight SVG file.
 * 3. When a CI/CD pipeline must automatically compress and clean up SVG assets generated by designers, the script can be invoked to validate file existence, optimize the vector paths, and produce a ready‑to‑deploy SVG.
 * 4. When an e‑mail marketing system requires small SVG graphics that render consistently across clients, developers can employ this code to load the original SVG, apply Aspose.Imaging rasterization options, and save a compact SVG for embedding.
 * 5. When a desktop publishing workflow needs to batch‑process SVG logos to remove unnecessary metadata and reduce file size before printing, this example shows how to programmatically load each SVG, simplify its vector data, and write the optimized file to a target folder.
 */