// HOW-TO: Batch Embed Digital Signatures into PNG Files with Shared Password in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Png;

namespace DigitalSignatureBatch
{
    class Program
    {
        static void Main()
        {
            // Hardcoded paths and password
            string inputDirectory = @"C:\Images\Input";
            string outputDirectory = @"C:\Images\Output";
            string password = "SharedPassword";

            try
            {
                // Ensure output base directory exists
                Directory.CreateDirectory(outputDirectory);

                // Get all PNG files in the input directory
                string[] pngFiles = Directory.GetFiles(inputDirectory, "*.png");

                foreach (string inputPath in pngFiles)
                {
                    // Validate input file existence
                    if (!File.Exists(inputPath))
                    {
                        Console.Error.WriteLine($"File not found: {inputPath}");
                        return;
                    }

                    // Load the image as a RasterImage
                    using (RasterImage image = (RasterImage)Image.Load(inputPath))
                    {
                        // Embed the digital signature using the shared password
                        image.EmbedDigitalSignature(password);

                        // Prepare output path
                        string outputPath = Path.Combine(outputDirectory, Path.GetFileName(inputPath));

                        // Ensure the directory for the output file exists
                        Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                        // Save the signed image
                        image.Save(outputPath);

                        // Log success
                        Console.WriteLine($"Signed and saved: {outputPath}");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to protect a large set of product photos by adding a password‑protected digital signature to each PNG before publishing them online.
 * 2. When a compliance team requires every PNG report generated by an automated system to be signed with a shared password for audit verification.
 * 3. When you are archiving scanned documents as PNGs and must embed a digital signature to guarantee their integrity during long‑term storage.
 * 4. When a mobile app uploads multiple PNG assets and you want to sign them in bulk on the server to prevent tampering.
 * 5. When a legal workflow demands that all PNG evidence files be digitally signed with a common password and logged for successful processing.
 */
