// HOW-TO: Batch Embed Digital Signatures into PNG Images with Size Validation in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Png;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output directories
            string inputFolder = @"C:\Images\Input";
            string outputFolder = @"C:\Images\Output";
            string password = "MySecretPwd";

            // Ensure output directory exists
            Directory.CreateDirectory(outputFolder);

            // Get all PNG files in the input folder
            string[] pngFiles = Directory.GetFiles(inputFolder, "*.png");

            foreach (string inputPath in pngFiles)
            {
                // Verify input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Load the image as a RasterImage
                using (RasterImage image = (RasterImage)Image.Load(inputPath))
                {
                    // Check minimum size requirement (8x8 pixels)
                    if (image.Width < 8 || image.Height < 8)
                    {
                        Console.Error.WriteLine($"Image too small (must be at least 8x8): {inputPath}");
                        continue;
                    }

                    // Embed the digital signature
                    image.EmbedDigitalSignature(password);

                    // Prepare output path
                    string outputPath = Path.Combine(outputFolder, Path.GetFileName(inputPath));

                    // Ensure the output directory exists
                    Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                    // Save the signed image
                    image.Save(outputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to protect a collection of PNG assets by embedding a password‑protected digital signature before distributing them.
 * 2. When an automated build pipeline must sign every PNG generated by a graphics tool to ensure authenticity and tamper‑evidence.
 * 3. When a compliance system requires that all uploaded PNG files be at least 8×8 pixels and carry a cryptographic signature.
 * 4. When a desktop application processes user‑provided screenshots and must embed a secret signature to track provenance.
 * 5. When a batch job has to sign multiple PNG files stored in a folder while preserving their original filenames and folder structure.
 */
