using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Wrap the whole logic to catch unexpected errors
        try
        {
            // Hard‑coded input files (PNG images) and output folder
            string[] inputPaths = new string[]
            {
                @"C:\Images\Input\image1.png",
                @"C:\Images\Input\image2.png",
                @"C:\Images\Input\image3.png"
            };

            // Output folder (same for all images)
            string outputFolder = @"C:\Images\Output";

            // Password used for the digital signature
            const string password = "MySecretPassword";

            // Ensure the output directory exists (unconditional as required)
            Directory.CreateDirectory(outputFolder);

            foreach (string inputPath in inputPaths)
            {
                // Verify the input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    continue; // Skip to next file
                }

                // Load the image using Aspose.Imaging
                using (Image image = Image.Load(inputPath))
                {
                    // Ensure the image is a raster image (PNG is raster)
                    if (image is RasterImage rasterImage)
                    {
                        // Check minimum size requirement (8×8 pixels)
                        if (rasterImage.Width < 8 || rasterImage.Height < 8)
                        {
                            Console.Error.WriteLine($"Image too small (minimum 8×8): {inputPath}");
                            continue; // Skip this image
                        }

                        // Embed the digital signature
                        rasterImage.EmbedDigitalSignature(password);

                        // Build output file path (preserve original name)
                        string outputPath = Path.Combine(outputFolder, Path.GetFileName(inputPath));

                        // Ensure the directory for the output file exists (already created above)
                        // Save the signed image
                        rasterImage.Save(outputPath);
                    }
                    else
                    {
                        Console.Error.WriteLine($"Unsupported image type: {inputPath}");
                    }
                }
            }
        }
        catch (Exception ex)
        {
            // Report any unexpected errors
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to securely watermark a collection of product catalog PNG thumbnails before publishing them to an e‑commerce site, they can use Aspose.Imaging for .NET to batch embed a digital signature while verifying each image meets the 8×8 pixel minimum.
 * 2. When an automated compliance pipeline must attach a tamper‑evident digital signature to PNG screenshots generated by a monitoring tool, the C# code can process multiple files, check raster dimensions, and embed the signature in one pass.
 * 3. When a mobile app backend prepares user‑uploaded PNG avatars for storage, it can enforce a minimum size and embed a password‑protected digital signature to guarantee image integrity using Aspose.Imaging’s EmbedDigitalSignature method.
 * 4. When a legal document management system converts scanned pages to PNG and needs to certify each page with a digital signature before archiving, the batch processing loop ensures every raster image is at least 8×8 pixels and signs them programmatically.
 * 5. When a DevOps script updates a set of PNG icons in a software distribution bundle, it can automatically embed a digital signature to prevent unauthorized modifications, leveraging C# file I/O and Aspose.Imaging’s size validation.
 */