using System;
using System.IO;
using Aspose.Imaging;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input and output directories
            string inputDir = @"C:\Images\Input";
            string outputDir = @"C:\Images\Output";
            string password = "sharedPassword";

            // Ensure the base output directory exists
            Directory.CreateDirectory(outputDir);

            // Get all PNG files in the input directory
            string[] pngFiles = Directory.GetFiles(inputDir, "*.png", SearchOption.TopDirectoryOnly);

            foreach (string inputPath in pngFiles)
            {
                // Verify the input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                string fileName = Path.GetFileName(inputPath);
                string outputPath = Path.Combine(outputDir, fileName);

                // Ensure the output directory for this file exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                using (Image image = Image.Load(inputPath))
                {
                    // Work with raster images to embed the digital signature
                    if (image is RasterImage rasterImage)
                    {
                        rasterImage.EmbedDigitalSignature(password);
                        rasterImage.Save(outputPath);
                        Console.WriteLine($"Signed: {fileName}");
                    }
                    else
                    {
                        Console.Error.WriteLine($"Unsupported image type: {inputPath}");
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer must protect a large collection of PNG assets by embedding a shared password‑protected digital signature before publishing them to a website.
 * 2. When an automated build pipeline needs to verify the integrity of all PNG icons generated by a design team by signing each file and logging the successful operations.
 * 3. When a compliance officer requires that every PNG screenshot stored in a regulatory archive be digitally signed with a common password to meet audit trail requirements.
 * 4. When a desktop application processes user‑uploaded PNG images and must batch‑sign them with a shared secret before saving them to a secure output folder.
 * 5. When a migration script moves PNG files from one server to another and needs to embed a password‑protected digital signature on each image to ensure they cannot be tampered with during transfer.
 */