// HOW-TO: Convert PNG to Truecolor With Alpha Using Aspose Imaging C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Png;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "input.png";
        string outputPath = "output.png";

        try
        {
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");

            using (RasterImage image = (RasterImage)Image.Load(inputPath))
            {
                var options = new PngOptions
                {
                    ColorType = PngColorType.TruecolorWithAlpha
                };
                image.Save(outputPath, options);
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to ensure a PNG image uses a true‑color (24‑bit) format with an alpha channel before uploading to a web site that requires full‑color transparency.
 * 2. When converting indexed‑color PNGs generated by legacy tools into a standard truecolor PNG so downstream image‑processing libraries can manipulate pixel data without palette limitations.
 * 3. When re‑encoding PNG assets for a game engine that only accepts TruecolorWithAlpha PNGs, guaranteeing consistent rendering of semi‑transparent sprites.
 * 4. When normalizing a collection of PNG files to the same color type to simplify batch operations such as resizing or applying filters in a C# image‑processing pipeline.
 * 5. When preserving existing transparency while reducing file size by re‑saving PNGs with Aspose.Imaging’s optimized TruecolorWithAlpha option.
 */
