using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main()
    {
        // Hardcoded source and destination folders
        string sourceFolder = @"C:\Images\Source";
        string destinationFolder = @"C:\Images\Output";

        try
        {
            // Get all BMP files in the source folder
            string[] bmpFiles = Directory.GetFiles(sourceFolder, "*.bmp");

            foreach (string inputPath in bmpFiles)
            {
                // Verify input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Build output path with .png extension, preserving filename
                string outputFileName = Path.GetFileNameWithoutExtension(inputPath) + ".png";
                string outputPath = Path.Combine(destinationFolder, outputFileName);

                // Ensure the output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                // Load BMP image and save as PNG
                using (Image image = Image.Load(inputPath))
                {
                    PngOptions pngOptions = new PngOptions();
                    image.Save(outputPath, pngOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to migrate a legacy collection of BMP assets to PNG for web delivery while keeping the original filenames.
 * 2. When an automated build script must batch‑convert BMP screenshots generated by a testing tool into lossless PNG files for archival.
 * 3. When a Windows service processes incoming BMP scans from a folder and saves them as PNG to reduce file size without changing naming conventions.
 * 4. When a photo‑management application imports a user’s BMP folder and normalizes all images to PNG for consistent format support across platforms.
 * 5. When a data‑migration utility prepares BMP graphics for a mobile app by converting them to PNG while preserving the original file names for reference.
 */