// HOW-TO: Blur A PSD Image With Gaussian Sigma 3 And Save As PDF In C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Psd;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Define input and output paths
            string inputPath = Path.Combine("Input", "sample.psd");
            string outputPath = Path.Combine("Output", "blurred.pdf");

            // Verify input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load the PSD image
            using (Image image = Image.Load(inputPath))
            {
                // Cast to RasterImage to apply filter
                RasterImage raster = (RasterImage)image;

                // Apply Gaussian blur with radius 5 and sigma 3.0
                raster.Filter(raster.Bounds,
                    new Aspose.Imaging.ImageFilters.FilterOptions.GaussianBlurFilterOptions(5, 3.0));

                // Save the processed image as PDF
                image.Save(outputPath, new PdfOptions());
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to soften the details of a Photoshop PSD before embedding it in a PDF report generated by a C# application.
 * 2. When a web service must automatically apply a Gaussian blur with sigma 3 to user‑uploaded PSD files and deliver the result as a PDF document.
 * 3. When creating printable catalogs where high‑resolution PSD artwork requires a subtle blur to protect copyrighted elements before conversion to PDF.
 * 4. When batch‑processing design assets in a .NET workflow to reduce file size and visual noise by blurring PSD layers and saving them as PDFs.
 * 5. When integrating Aspose.Imaging into a C# desktop tool that prepares marketing materials by smoothing PSD images and exporting them directly to PDF format.
 */
