using System;
using System.IO;
using System.Collections.Generic;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Hardcoded input and output paths
            string cdrPath = "Input/sample.cdr";
            string tiffPath = "Input/sample.tif";
            string outputPath = "Output/combined.pdf";

            // Validate input files
            if (!File.Exists(cdrPath))
            {
                Console.Error.WriteLine($"File not found: {cdrPath}");
                return;
            }
            if (!File.Exists(tiffPath))
            {
                Console.Error.WriteLine($"File not found: {tiffPath}");
                return;
            }

            // Ensure output directory exists
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            // Load source images
            using (Image cdrImage = Image.Load(cdrPath))
            using (Image tiffImage = Image.Load(tiffPath))
            {
                List<Image> pages = new List<Image>();

                // Add pages from CDR image
                if (cdrImage is IMultipageImage cdrMultipage && cdrMultipage.Pages != null)
                {
                    foreach (var page in cdrMultipage.Pages)
                    {
                        pages.Add(page);
                    }
                }
                else
                {
                    pages.Add(cdrImage);
                }

                // Add pages from TIFF image
                if (tiffImage is IMultipageImage tiffMultipage && tiffMultipage.Pages != null)
                {
                    foreach (var page in tiffMultipage.Pages)
                    {
                        pages.Add(page);
                    }
                }
                else
                {
                    pages.Add(tiffImage);
                }

                // Create a new multipage image from collected pages
                using (Image combined = Image.Create(pages.ToArray()))
                {
                    PdfOptions pdfOptions = new PdfOptions();
                    combined.Save(outputPath, pdfOptions);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a designer needs to merge multi‑page CorelDRAW (CDR) artwork with scanned multi‑page TIFF documents into a single searchable PDF for client delivery, this code automates the combination.
 * 2. When an archival system must consolidate vector‑based CDR diagrams and raster TIFF scans into one PDF file for long‑term storage and easy retrieval, the example provides a programmatic solution.
 * 3. When a reporting tool has to embed both multi‑page CDR illustrations and multi‑page TIFF charts into a unified PDF report generated by a C# backend, this code handles the page aggregation.
 * 4. When a workflow requires converting mixed‑format source files—vector CDR pages and raster TIFF pages—into a single PDF for printing or electronic distribution, the snippet demonstrates the necessary steps.
 * 5. When a document management application needs to import multi‑page CDR and TIFF assets, combine their pages, and export them as a PDF to maintain page order and format fidelity, this code fulfills that requirement.
 */