// HOW-TO: Batch Convert PNG Sequence to APNG with Status Report in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Apng;
using Aspose.Imaging.FileFormats.Png;
using Aspose.Imaging.Sources;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            // Input and output directories (relative)
            string inputDirectory = "Input";
            string outputDirectory = "Output";

            // Ensure input directory exists
            if (!Directory.Exists(inputDirectory))
            {
                Directory.CreateDirectory(inputDirectory);
                Console.WriteLine($"Input directory created at: {inputDirectory}. Add PNG files and rerun.");
                return;
            }

            // Ensure output directory exists
            if (!Directory.Exists(outputDirectory))
            {
                Directory.CreateDirectory(outputDirectory);
            }

            // Get all PNG files in the input directory
            string[] pngFiles = Directory.GetFiles(inputDirectory, "*.png");

            // Path for the conversion report
            string reportPath = Path.Combine(outputDirectory, "report.txt");
            Directory.CreateDirectory(Path.GetDirectoryName(reportPath));

            using (StreamWriter reportWriter = new StreamWriter(reportPath, false))
            {
                foreach (string inputPath in pngFiles)
                {
                    // Validate input file existence
                    if (!File.Exists(inputPath))
                    {
                        Console.Error.WriteLine($"File not found: {inputPath}");
                        reportWriter.WriteLine($"{Path.GetFileName(inputPath)} -> N/A: Input file not found");
                        continue;
                    }

                    // Determine output file path
                    string fileNameWithoutExt = Path.GetFileNameWithoutExtension(inputPath);
                    string outputPath = Path.Combine(outputDirectory, fileNameWithoutExt + ".apng.png");

                    // Ensure output directory for this file exists
                    Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                    try
                    {
                        // Load source PNG as raster image
                        using (RasterImage sourceImage = (RasterImage)Image.Load(inputPath))
                        {
                            // Configure APNG creation options
                            ApngOptions options = new ApngOptions
                            {
                                Source = new FileCreateSource(outputPath, false),
                                DefaultFrameTime = 100, // 100 ms per frame
                                ColorType = PngColorType.TruecolorWithAlpha
                            };

                            // Create APNG image canvas
                            using (ApngImage apngImage = (ApngImage)Image.Create(options, sourceImage.Width, sourceImage.Height))
                            {
                                // Remove the default single frame
                                apngImage.RemoveAllFrames();

                                // Add multiple frames (e.g., 5 copies of the source)
                                int frameCount = 5;
                                for (int i = 0; i < frameCount; i++)
                                {
                                    apngImage.AddFrame(sourceImage);
                                    // Optional: adjust gamma per frame
                                    ApngFrame frame = (ApngFrame)apngImage.Pages[apngImage.PageCount - 1];
                                    frame.AdjustGamma((float)i);
                                }

                                // Save the APNG file
                                apngImage.Save();
                            }
                        }

                        reportWriter.WriteLine($"{Path.GetFileName(inputPath)} -> {Path.GetFileName(outputPath)}: Success");
                    }
                    catch (Exception ex)
                    {
                        Console.Error.WriteLine($"Error processing {inputPath}: {ex.Message}");
                        reportWriter.WriteLine($"{Path.GetFileName(inputPath)} -> {Path.GetFileName(outputPath)}: Failed - {ex.Message}");
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to combine a series of PNG frames generated by a game engine into a single animated PNG for web delivery while tracking which files were successfully processed.
 * 2. When an automated build pipeline must create APNG assets from design‑team PNG exports and produce a text report for QA to verify conversion results.
 * 3. When a desktop application processes user‑uploaded PNG image sequences and saves them as APNG files, logging any missing or corrupt files for later troubleshooting.
 * 4. When a server‑side service generates animated stickers from individual PNG layers and records each conversion’s status to a report for monitoring and auditing.
 * 5. When a batch script converts thousands of PNG screenshots into APNG animations for documentation and needs a concise report indicating success or failure of each file.
 */
