// HOW-TO: Convert Multi‑Page TIFF to Animated PNG Using Page Resolution in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Tiff;
using Aspose.Imaging.FileFormats.Apng;
using Aspose.Imaging.FileFormats.Png;
using Aspose.Imaging.Sources;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "input.tif";
            string outputPath = "output.apng";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            string outputDir = Path.GetDirectoryName(outputPath);
            if (!string.IsNullOrWhiteSpace(outputDir))
            {
                Directory.CreateDirectory(outputDir);
            }

            using (TiffImage tiff = (TiffImage)Image.Load(inputPath))
            {
                int width = tiff.Width;
                int height = tiff.Height;

                ApngOptions apngOptions = new ApngOptions
                {
                    Source = new FileCreateSource(outputPath, false),
                    ColorType = PngColorType.TruecolorWithAlpha
                };

                using (ApngImage apng = (ApngImage)Image.Create(apngOptions, width, height))
                {
                    apng.RemoveAllFrames();

                    int pageCount = tiff.Frames.Count();
                    for (int i = 0; i < pageCount; i++)
                    {
                        RasterImage pageImg = (RasterImage)tiff.Frames[i];
                        apng.AddFrame(pageImg);
                    }

                    apng.Save();
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to transform a scanned multi‑page TIFF document into an animated PNG that can be displayed directly in web browsers.
 * 2. When you want each TIFF page to become a separate frame in an APNG and have the frame duration automatically reflect the original page resolution.
 * 3. When building a .NET reporting tool that converts medical imaging TIFF stacks into lightweight APNG animations for quick visual review.
 * 4. When automating the conversion of multi‑page TIFF files generated by scanners into APNGs that preserve page order and timing for online galleries.
 * 5. When creating a desktop application that generates step‑by‑step animated PNG tutorials from a series of TIFF slides, using Aspose.Imaging for C#.
 */
