using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.FileFormats.Apng;

class Program
{
    static void Main()
    {
        try
        {
            // Hardcoded input path
            string inputPath = "input.apng";

            // Verify that the input file exists
            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            // Load the image
            using (Image image = Image.Load(inputPath))
            {
                // Cast to ApngImage to access APNG-specific properties
                ApngImage apngImage = image as ApngImage;
                if (apngImage == null)
                {
                    Console.Error.WriteLine("The specified file is not an APNG image.");
                    return;
                }

                // Retrieve loop count (NumPlays) and total frame count (PageCount)
                int loopCount = apngImage.NumPlays; // 0 means infinite looping
                int frameCount = apngImage.PageCount;

                // Display the metadata
                string loopInfo = loopCount == 0 ? "Infinite" : loopCount.ToString();
                Console.WriteLine($"Loop count: {loopInfo}");
                Console.WriteLine($"Total frames: {frameCount}");
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to display the animation settings of an APNG file—such as its loop count and total number of frames—in a C# desktop application using Aspose.Imaging for .NET.
 * 2. When building a media catalog or asset management system that extracts APNG metadata to sort or filter animated images based on how many times they repeat and how many frames they contain.
 * 3. When validating user‑uploaded APNG files on a web service to ensure they meet specific animation requirements, like a maximum frame count or a finite loop count, using C# and Aspose.Imaging.
 * 4. When generating a preview panel in a graphics editor that shows the loop count (including infinite looping) and frame count of an APNG before the user edits or exports the animation.
 * 5. When creating automated test scripts that verify that an APNG generated by a rendering pipeline has the expected number of frames and the correct NumPlays value, leveraging Aspose.Imaging’s APNG support in .NET.
 */