// HOW-TO: Convert EPS to PNG, JPG, PDF, SVG, or PSD in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

namespace EpsConverter
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                // Hardcoded input and base output paths
                string inputPath = "input.eps";
                string format = args[0]; // No args.Length validation per priority rules
                string outputPath = $"output.{format}";

                // Verify input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Ensure output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");

                // Load EPS image
                using (Image image = Image.Load(inputPath))
                {
                    switch (format.ToLower())
                    {
                        case "png":
                            var pngOptions = new PngOptions();
                            image.Save(outputPath, pngOptions);
                            break;
                        case "jpg":
                        case "jpeg":
                            var jpegOptions = new JpegOptions();
                            image.Save(outputPath, jpegOptions);
                            break;
                        case "pdf":
                            var pdfOptions = new PdfOptions();
                            image.Save(outputPath, pdfOptions);
                            break;
                        case "svg":
                            var svgOptions = new SvgOptions();
                            image.Save(outputPath, svgOptions);
                            break;
                        case "psd":
                            var psdOptions = new PsdOptions();
                            image.Save(outputPath, psdOptions);
                            break;
                        default:
                            Console.Error.WriteLine($"Unsupported format: {format}");
                            return;
                    }
                }

                Console.WriteLine($"Conversion completed: {outputPath}");
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"Error: {ex.Message}");
            }
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to batch‑convert legacy EPS artwork to web‑friendly PNG or JPEG images in a C# automation script.
 * 2. When a reporting tool must embed vector EPS diagrams into PDF documents generated by a .NET application.
 * 3. When an e‑commerce platform requires converting EPS logos to scalable SVG files for responsive web design.
 * 4. When a digital asset management system needs to store EPS files as Photoshop PSD layers for further editing.
 * 5. When a command‑line utility must allow users to specify the desired output format for EPS conversion at runtime.
 */
