// HOW-TO: Create Image Conversion README With Aspose.Imaging For .NET (Aspose.Imaging for .NET)
using System;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string outputPath = Path.Combine("Output", "README.md");
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));
            string content = @"# Aspose.Imaging Conversion Guide

This README provides developers with step‑by‑step instructions for performing common image format conversions using Aspose.Imaging for .NET.

## Prerequisites
- Add a reference to **Aspose.Imaging** NuGet package.
- Include the required namespaces in your code (example):
```csharp
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
```

## Basic Conversion Pattern
```csharp
using (Image image = Image.Load(inputPath))
{
    // Choose the appropriate options class for the target format
    // Example: convert to JPEG
    var options = new JpegOptions();
    image.Save(outputPath, options);
}
```

## Supported Formats
| Source | Target | Options Class |
|--------|--------|---------------|
| PNG    | JPEG   | JpegOptions   |
| JPEG   | PNG    | PngOptions    |
| BMP    | TIFF   | TiffOptions   |
| GIF    | PDF    | PdfOptions    |
| ...    | ...    | ...           |

## Example: PNG to JPEG
```csharp
string inputPath = ""Input/sample.png"";
string outputPath = ""Output/sample.jpg"";

using (Image image = Image.Load(inputPath))
{
    var jpegOptions = new JpegOptions
    {
        Quality = 90
    };
    image.Save(outputPath, jpegOptions);
}
```

## Batch Conversion
```csharp
string baseDir = Directory.GetCurrentDirectory();
string inputDir = Path.Combine(baseDir, ""Input"");
string outputDir = Path.Combine(baseDir, ""Output"");

// Ensure directories exist
if (!Directory.Exists(inputDir))
{
    Directory.CreateDirectory(inputDir);
    Console.WriteLine($""Input directory created at: {inputDir}. Add files and rerun."");
    return;
}
if (!Directory.Exists(outputDir))
{
    Directory.CreateDirectory(outputDir);
}

// Process each file
foreach (string file in Directory.GetFiles(inputDir, ""*.png""))
{
    string fileName = Path.GetFileNameWithoutExtension(file);
    string outPath = Path.Combine(outputDir, fileName + "".jpg"");

    using (Image img = Image.Load(file))
    {
        var opts = new JpegOptions { Quality = 80 };
        img.Save(outPath, opts);
    }
}
```

## Advanced Scenarios
- **Grayscale conversion**: `rci.Grayscale();`
- **Binarization**: `rci.BinarizeFixed(128);` or `rci.BinarizeOtsu();`
- **Vector to raster**: configure `VectorRasterizationOptions` on the target options.
- **PDF export**: use `PdfOptions` with optional `PdfDocumentInfo`.

Refer to the official Aspose.Imaging documentation for detailed API usage and additional options.

---  
Generated by the Aspose.Imaging conversion helper.";
            File.WriteAllText(outputPath, content);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to automatically generate a Markdown README that outlines how to convert PNG, JPEG, BMP, and GIF images using Aspose.Imaging in a .NET project.
 * 2. When setting up a new repository and want to include step‑by‑step code samples for common image format conversions so team members can quickly start using the library.
 * 3. When creating CI/CD pipelines that produce up‑to‑date documentation on supported source and target formats without manually editing the guide.
 * 4. When providing non‑technical stakeholders with a clear, printable guide that shows required NuGet packages, namespace imports, and sample conversion code.
 * 5. When building a reusable template that can be copied into multiple micro‑services to ensure consistent image conversion instructions across the organization.
 */
