// HOW-TO: Convert EPS to PDF with Aspose.Imaging in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;
using Aspose.Imaging.FileFormats.Pdf;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "input.eps";
            string outputPath = "output.pdf";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                image.Save(outputPath, new PdfOptions());
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to programmatically turn EPS vector artwork into PDF documents for web preview or printing using C# and Aspose.Imaging.
 * 2. When a batch job must convert a folder of EPS files to searchable PDFs on a server without manual intervention.
 * 3. When you want to embed EPS‑based diagrams into PDF reports generated by a .NET application.
 * 4. When an e‑commerce platform requires EPS logos to be delivered as PDF files for customer downloads.
 * 5. When an automated email system needs to attach PDFs created from EPS files to ensure compatibility across recipients.
 */
