// HOW-TO: Convert EPS File to PDF Using Aspose.Imaging in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageOptions;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            string inputPath = "Input/epsFile.eps";
            string outputPath = "Output/converted.pdf";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            using (Image image = Image.Load(inputPath))
            {
                image.Save(outputPath, new PdfOptions());
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to embed a vector EPS illustration into a PDF report generated by a .NET application.
 * 2. When a web service receives EPS artwork and must provide a PDF version for client download.
 * 3. When automating batch conversion of legacy EPS assets to PDF for archival or printing workflows.
 * 4. When integrating Aspose.Imaging into a document management system to standardize all graphics as PDF.
 * 5. When creating a PDF catalog that includes EPS logos and diagrams without losing quality.
 */
