// HOW-TO: Apply Sharpen 3x3 Filter to All SVG Frames in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using System.Xml.Linq;

class Program
{
    static void Main()
    {
        try
        {
            string inputPath = "input.svg";
            string outputPath = "output.svg";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? string.Empty);

            XDocument doc = XDocument.Load(inputPath);
            XNamespace ns = "http://www.w3.org/2000/svg";

            // Ensure <defs> exists
            XElement defs = doc.Root.Element(ns + "defs");
            if (defs == null)
            {
                defs = new XElement(ns + "defs");
                doc.Root.AddFirst(defs);
            }

            // Add sharpen filter if not already present
            const string filterId = "sharpen3x3";
            XElement existingFilter = defs.Element(ns + "filter");
            if (existingFilter == null || (string)existingFilter.Attribute("id") != filterId)
            {
                XElement filter = new XElement(ns + "filter",
                    new XAttribute("id", filterId),
                    new XElement(ns + "feConvolveMatrix",
                        new XAttribute("order", "3"),
                        new XAttribute("kernelMatrix", "0 -1 0 -1 5 -1 0 -1 0"),
                        new XAttribute("divisor", "1"),
                        new XAttribute("bias", "0"),
                        new XAttribute("preserveAlpha", "true")
                    )
                );
                defs.Add(filter);
            }

            // Apply filter to each top-level <svg> element (including root)
            foreach (XElement svgElem in doc.Descendants(ns + "svg"))
            {
                svgElem.SetAttributeValue("filter", $"url(#{filterId})");
            }

            // Also apply to the root if it's an <svg>
            if (doc.Root.Name == ns + "svg")
            {
                doc.Root.SetAttributeValue("filter", $"url(#{filterId})");
            }

            doc.Save(outputPath);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to enhance the visual clarity of each page in a multi‑page SVG before embedding it in a web report.
 * 2. When you want to programmatically add a sharpening effect to all layers of an SVG generated by a CAD tool.
 * 3. When you must ensure consistent image sharpness across all frames of an animated SVG used in a UI animation.
 * 4. When you are automating a batch process that improves the detail of SVG icons stored in a design system.
 * 5. When you need to insert a custom SVG filter and apply it to every SVG element in a document for print‑ready graphics.
 */
