// HOW-TO: Batch Deconvolution of Blurred PNG Images Using Aspose.Imaging in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageFilters.FilterOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hard‑coded list of blurred PNG files to process
            string[] inputPaths = new string[]
            {
                @"C:\Images\blur1.png",
                @"C:\Images\blur2.png",
                @"C:\Images\blur3.png"
            };

            foreach (string inputPath in inputPaths)
            {
                // Verify that the input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    continue;
                }

                // Build output path – same folder, with "_restored" suffix
                string outputPath = Path.Combine(
                    Path.GetDirectoryName(inputPath),
                    Path.GetFileNameWithoutExtension(inputPath) + "_restored.png");

                // Ensure the output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                // Load the PNG image
                using (Image image = Image.Load(inputPath))
                {
                    // Cast to RasterImage to use the Filter method
                    RasterImage rasterImage = (RasterImage)image;

                    // Create deconvolution filter options (default parameters)
                    var deconvOptions = new MotionWienerFilterOptions(5, 1.0, 0.0);

                    // Apply the deconvolution filter to the whole image
                    rasterImage.Filter(rasterImage.Bounds, deconvOptions);

                    // Save the restored image
                    rasterImage.Save(outputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to automatically sharpen a collection of motion‑blurred PNG photos before uploading them to a web gallery.
 * 2. When a desktop application must restore scanned documents that appear fuzzy due to camera shake, processing each file in a folder with C#.
 * 3. When a batch job has to improve the visual quality of PNG assets generated by a simulation that introduced blur, using Aspose.Imaging’s default deconvolution filter.
 * 4. When an automated pipeline requires saving restored versions of PNG screenshots with a “_restored” suffix for later comparison or archiving.
 * 5. When you want to integrate simple image deblurring into a C# service without manually configuring filter parameters for each image.
 */
