using System;
using System.IO;
using Aspose.Imaging;
using Aspose.Imaging.ImageFilters.FilterOptions;

class Program
{
    static void Main()
    {
        try
        {
            // Hard‑coded input and output directories
            string inputDirectory = @"C:\Images\Input";
            string outputDirectory = @"C:\Images\Output";

            // Process every PNG file in the input directory
            foreach (string inputPath in Directory.GetFiles(inputDirectory, "*.png"))
            {
                // Verify the input file exists
                if (!File.Exists(inputPath))
                {
                    Console.Error.WriteLine($"File not found: {inputPath}");
                    return;
                }

                // Preserve the original file name
                string fileName = Path.GetFileName(inputPath);
                string outputPath = Path.Combine(outputDirectory, fileName);

                // Ensure the output directory exists
                Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

                // Load the image, apply the 5x5 sharpen filter, and save it
                using (Image image = Image.Load(inputPath))
                {
                    var rasterImage = (RasterImage)image;

                    // Apply a sharpen filter with a 5×5 kernel (size = 5, sigma = 0)
                    rasterImage.Filter(rasterImage.Bounds, new SharpenFilterOptions(5, 0));

                    rasterImage.Save(outputPath);
                }
            }
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to automatically enhance the sharpness of a large collection of PNG product photos before uploading them to an e‑commerce site, they can use this code to batch apply a 5×5 sharpen filter while preserving original file names.
 * 2. When a C# application must prepare PNG screenshots for a documentation portal by improving edge definition without altering filenames, this script provides a simple way to process the entire folder in one run.
 * 3. When a photo‑editing workflow requires consistent sharpening of PNG assets generated by a graphics pipeline, the code can be integrated to apply the Sharpen5x5 filter to every file in a directory and save the results to a separate output folder.
 * 4. When a developer is building a batch image‑processing tool that needs to read PNG files, apply a raster filter, and keep the original naming scheme for downstream indexing, this example demonstrates the required Aspose.Imaging operations.
 * 5. When an automated build process must improve the visual clarity of PNG icons used in a Windows application before packaging, the program can be scheduled to run and apply the 5×5 sharpen filter to all icons in the source folder.
 */