// HOW-TO: Add Gaussian Blur Filter to SVG with Sigma 2.8 in C# (Aspose.Imaging for .NET)
using System;
using System.IO;
using System.Xml.Linq;

class Program
{
    static void Main()
    {
        try
        {
            string inputPath = "input.svg";
            string outputPath = "output.svg";

            if (!File.Exists(inputPath))
            {
                Console.Error.WriteLine($"File not found: {inputPath}");
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");

            XDocument doc = XDocument.Load(inputPath);
            XNamespace ns = "http://www.w3.org/2000/svg";

            XElement defs = doc.Root.Element(ns + "defs");
            if (defs == null)
            {
                defs = new XElement(ns + "defs");
                doc.Root.AddFirst(defs);
            }

            // Remove any existing filter with the same id
            foreach (var existing in defs.Elements(ns + "filter"))
            {
                if ((string)existing.Attribute("id") == "gaussianBlur")
                {
                    existing.Remove();
                    break;
                }
            }

            XElement filter = new XElement(ns + "filter",
                new XAttribute("id", "gaussianBlur"),
                new XElement(ns + "feGaussianBlur",
                    new XAttribute("stdDeviation", "2.8")
                )
            );

            defs.Add(filter);
            doc.Root.SetAttributeValue("filter", "url(#gaussianBlur)");

            doc.Save(outputPath);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }

    static double[,] GenerateGaussianKernel(double sigma)
    {
        int radius = (int)Math.Ceiling(3 * sigma);
        int size = radius * 2 + 1;
        double[,] kernel = new double[size, size];
        double twoSigmaSq = 2 * sigma * sigma;
        double sum = 0;

        for (int y = -radius; y <= radius; y++)
        {
            for (int x = -radius; x <= radius; x++)
            {
                double value = Math.Exp(-(x * x + y * y) / twoSigmaSq);
                kernel[y + radius, x + radius] = value;
                sum += value;
            }
        }

        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                kernel[y, x] /= sum;
            }
        }

        return kernel;
    }
}

/*
 * Real-World Use Cases:
 * 1. When you need to programmatically add a Gaussian blur effect to an SVG icon before embedding it in a web page.
 * 2. When you must generate a custom blur radius (sigma 2.8) for vector graphics used in a PDF report generated by C#.
 * 3. When an automated build process has to apply consistent softening to all SVG assets in a design system without manual editing.
 * 4. When a desktop application creates SVG thumbnails and wants to smooth edges by applying a filter defined in the SVG markup.
 * 5. When you are converting raster images to SVG and need to preserve a blur effect by inserting a feGaussianBlur element via C# code.
 */
