using System;
using System.IO;

class Program
{
    static void Main(string[] args)
    {
        string inputPath = "input.txt";
        string outputPath = "output.txt";

        if (!File.Exists(inputPath))
        {
            Console.Error.WriteLine($"File not found: {inputPath}");
            return;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? ".");

        try
        {
            int size = 5;
            double sigma = 1.0;
            double[,] kernel = Aspose.Imaging.ImageFilters.Convolution.ConvolutionFilter.GetGaussian(size, sigma);
            Console.WriteLine($"Gaussian kernel (size={size}, sigma={sigma}):");
            int rows = kernel.GetLength(0);
            int cols = kernel.GetLength(1);
            for (int i = 0; i < rows; i++)
            {
                for (int j = 0; j < cols; j++)
                {
                    Console.Write(kernel[i, j]);
                    if (j < cols - 1) Console.Write(", ");
                }
                if (i < rows - 1) Console.WriteLine();
            }
            Console.WriteLine();
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine($"Error: {ex.Message}");
        }
    }
}

/*
 * Real-World Use Cases:
 * 1. When a developer needs to apply a subtle Gaussian blur to a JPEG or PNG image before resizing it to reduce aliasing artifacts, they can generate a 5×5 kernel with sigma 1.0 using Aspose.Imaging’s ConvolutionFilter.GetGaussian.
 * 2. When building a C# console tool that extracts edge information from scanned TIFF documents, the code can create a small Gaussian kernel to smooth the image prior to applying a Sobel filter.
 * 3. When implementing a custom image sharpening routine for BMP sprites in a game, a developer may first generate a 5‑pixel Gaussian blur kernel to blur the sprite and then subtract it to enhance details.
 * 4. When creating a batch processing pipeline that converts PDF pages to PNG and needs consistent softening of background gradients, the Gaussian kernel generated by GetGaussian provides the required low‑frequency blur.
 * 5. When writing unit tests for Aspose.Imaging’s convolution operations, a developer can use the 5×5 sigma 1.0 kernel as a known reference to verify that the filter produces the expected blurred output on sample images.
 */